// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &WirelessWLANProfileDataSource{}
	_ datasource.DataSourceWithConfigure = &WirelessWLANProfileDataSource{}
)

func NewWirelessWLANProfileDataSource() datasource.DataSource {
	return &WirelessWLANProfileDataSource{}
}

type WirelessWLANProfileDataSource struct {
	data *IosxeProviderData
}

func (d *WirelessWLANProfileDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_wlan_profile"
}

func (d *WirelessWLANProfileDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Wireless WLAN Profile configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"profile_name": schema.StringAttribute{
				MarkdownDescription: "profile-name",
				Required:            true,
			},
			"wlan_id": schema.Int64Attribute{
				MarkdownDescription: "wlan ID",
				Computed:            true,
			},
			"ssid": schema.StringAttribute{
				MarkdownDescription: "Represents the SSID assigned to this WLAN. The access points will broadcast this SSID on this WLAN. SSID is restricted to non control characters.",
				Computed:            true,
			},
			"wlan_status": schema.BoolAttribute{
				MarkdownDescription: "Administrative Status of ESS(WLAN). By disabling an ESS the corresponding SSID is no longer broadcasted in AP beacons.",
				Computed:            true,
			},
			"broadcast_ssid": schema.BoolAttribute{
				MarkdownDescription: "broadcast SSID on a WLAN",
				Computed:            true,
			},
			"ccx_aironet_iesupport": schema.BoolAttribute{
				MarkdownDescription: "This object indicates the support for the Cisco Compatible Extensions Aironet information element on this WLAN.",
				Computed:            true,
			},
			"peer_blocking": schema.StringAttribute{
				MarkdownDescription: "Represents the name of the ACL applied to this WLAN. If it is required to remove the ACL",
				Computed:            true,
			},
			"security_wpa_akm_dot1x": schema.BoolAttribute{
				MarkdownDescription: "Authentication key management type 802.1x",
				Computed:            true,
			},
			"security_wpa_akm_ft_dot1x": schema.BoolAttribute{
				MarkdownDescription: "Authentication key management type 802.11r dot1x",
				Computed:            true,
			},
			"security_wpa_akm_psk": schema.BoolAttribute{
				MarkdownDescription: "Authentication key management PSK",
				Computed:            true,
			},
			"security_wpa_akm_ft_psk": schema.BoolAttribute{
				MarkdownDescription: "Authentication key management type 802.11r PSK",
				Computed:            true,
			},
			"security_wpa_akm_sae": schema.BoolAttribute{
				MarkdownDescription: "Authentication key management type SAE",
				Computed:            true,
			},
			"security_wpa_akm_ft_sae": schema.BoolAttribute{
				MarkdownDescription: "Authentication key management type FT-SAE",
				Computed:            true,
			},
			"security_wpa_wpa2_ciphers_aes": schema.BoolAttribute{
				MarkdownDescription: "WPA2/CCMP128 support",
				Computed:            true,
			},
			"security_wpa_wpa2_ciphers_gcmp128": schema.BoolAttribute{
				MarkdownDescription: "WPA2/GCMP128 support",
				Computed:            true,
			},
			"security_wpa_wpa2_ciphers_gcmp256": schema.BoolAttribute{
				MarkdownDescription: "WPA2/GCMP256 support",
				Computed:            true,
			},
			"security_wpa_wpa3": schema.BoolAttribute{
				MarkdownDescription: "Configures WPA3 support",
				Computed:            true,
			},
			"security_wpa_psk_key_format": schema.StringAttribute{
				MarkdownDescription: "Authentication pre-shared key type ascii/hex",
				Computed:            true,
			},
			"security_wpa_psk_key_encryption": schema.StringAttribute{
				MarkdownDescription: "Pre-shared key encryption type",
				Computed:            true,
			},
			"security_wpa_psk_key": schema.StringAttribute{
				MarkdownDescription: "Authentication pre-shared key. For hexadecimal key format, PSK length must be exactly 64 characters and for ASCII key format, PSK length must be in the range of 8 and 63",
				Computed:            true,
				Sensitive:           true,
			},
			"security_dot1x_authentication_list": schema.StringAttribute{
				MarkdownDescription: "Enter the Authentication list name",
				Computed:            true,
			},
			"security_web_auth": schema.BoolAttribute{
				MarkdownDescription: "Configures Web authentication",
				Computed:            true,
			},
			"security_web_auth_authentication_list": schema.StringAttribute{
				MarkdownDescription: "Enter the Authentication list name",
				Computed:            true,
			},
			"security_web_auth_parameter_map": schema.StringAttribute{
				MarkdownDescription: "Enter the parameter-map name",
				Computed:            true,
			},
			"security_ft": schema.StringAttribute{
				MarkdownDescription: "Configures Fast Transition Adaptive support",
				Computed:            true,
			},
			"security_ft_over_the_ds": schema.BoolAttribute{
				MarkdownDescription: "Configures Fast Transition over the DS",
				Computed:            true,
			},
			"mac_filtering": schema.StringAttribute{
				MarkdownDescription: "Set MAC filtering support on WLAN",
				Computed:            true,
			},
			"load_balance": schema.BoolAttribute{
				MarkdownDescription: "Allow/Disallow Load Balance on a WLAN",
				Computed:            true,
			},
			"wmm": schema.StringAttribute{
				MarkdownDescription: "Configures WMM (WME)",
				Computed:            true,
			},
		},
	}
}

func (d *WirelessWLANProfileDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *WirelessWLANProfileDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config WirelessWLANProfileData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
