// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeWirelessAPJoinProfile(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "description", "S3 AP Join Profile Test"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_window_size", "5"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "country", "us"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "ssh", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "mgmtuser_username", "apadmin"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "mgmtuser_password_type", "clear"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "mgmtuser_secret_type", "clear"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "ntp_ip", "10.10.10.5"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "syslog_host", "10.10.10.6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "syslog_facility", "facility-local6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "syslog_level", "syslog-level-warning"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "apphost", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "association_limit", "200"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "awips", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "awips_forensic", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_retransmit_count", "5"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_retransmit_interval", "3"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_timers_discovery_timeout", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_timers_fast_heartbeat_timeout", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_timers_heartbeat_timeout", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_timers_primary_discovery_timeout", "60"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_timers_primed_join_timeout", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_backup_primary_name", "wlc-dc1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_backup_primary_ip", "10.10.10.11"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_backup_secondary_name", "wlc-dc2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_backup_secondary_ip", "10.20.20.11"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_fallback", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_discovery_private", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "capwap_discovery_public", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "cdp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "dot1x_eap_type", "dot1x-eap-tls"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "dot1x_username", "apuser"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "dot1x_password_type", "clear"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "hyperlocation", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "ip_dhcp_fallback", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "lag", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "led", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "mesh_profile", "default-mesh-profile"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "rogue_detection_enable", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "rogue_detection_min_rssi", "-80"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "rogue_detection_min_transient_time", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "rogue_detection_report_interval", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_system_monitoring_enable", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_system_monitoring_alarm_enable", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_system_monitoring_alarm_hold_time", "6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_system_monitoring_alarm_retransmit_time", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_system_monitoring_cpu_threshold", "90"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_system_monitoring_mem_threshold", "90"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_system_monitoring_sampling_interval", "30"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_system_monitoring_stats_interval", "300"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_traffic_distribution", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_traffic_distribution_interval", "300"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_radio_monitoring_enable", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "statistics_ap_radio_monitoring_sampling_interval", "720"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "stats_timer", "180"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "tcp_adjust_mss_enable", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "tcp_adjust_mss_size", "1250"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_ap_join_profile.test", "ble_scan", "false"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeWirelessAPJoinProfileConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeWirelessAPJoinProfileConfig() string {
	config := `resource "iosxe_wireless_ap_join_profile" "test" {` + "\n"
	config += `	name = "S3-AP-JOIN-1"` + "\n"
	config += `	description = "S3 AP Join Profile Test"` + "\n"
	config += `	capwap_window_size = 5` + "\n"
	config += `	country = "us"` + "\n"
	config += `	ssh = true` + "\n"
	config += `	mgmtuser_username = "apadmin"` + "\n"
	config += `	mgmtuser_password = "CiscoPass123!"` + "\n"
	config += `	mgmtuser_password_type = "clear"` + "\n"
	config += `	mgmtuser_secret = "CiscoSecret123!"` + "\n"
	config += `	mgmtuser_secret_type = "clear"` + "\n"
	config += `	ntp_ip = "10.10.10.5"` + "\n"
	config += `	syslog_host = "10.10.10.6"` + "\n"
	config += `	syslog_facility = "facility-local6"` + "\n"
	config += `	syslog_level = "syslog-level-warning"` + "\n"
	config += `	apphost = true` + "\n"
	config += `	association_limit = 200` + "\n"
	config += `	awips = true` + "\n"
	config += `	awips_forensic = true` + "\n"
	config += `	capwap_retransmit_count = 5` + "\n"
	config += `	capwap_retransmit_interval = 3` + "\n"
	config += `	capwap_timers_discovery_timeout = 10` + "\n"
	config += `	capwap_timers_fast_heartbeat_timeout = 1` + "\n"
	config += `	capwap_timers_heartbeat_timeout = 10` + "\n"
	config += `	capwap_timers_primary_discovery_timeout = 60` + "\n"
	config += `	capwap_timers_primed_join_timeout = 0` + "\n"
	config += `	capwap_backup_primary_name = "wlc-dc1"` + "\n"
	config += `	capwap_backup_primary_ip = "10.10.10.11"` + "\n"
	config += `	capwap_backup_secondary_name = "wlc-dc2"` + "\n"
	config += `	capwap_backup_secondary_ip = "10.20.20.11"` + "\n"
	config += `	capwap_fallback = true` + "\n"
	config += `	capwap_discovery_private = true` + "\n"
	config += `	capwap_discovery_public = false` + "\n"
	config += `	cdp = true` + "\n"
	config += `	dot1x_eap_type = "dot1x-eap-tls"` + "\n"
	config += `	dot1x_username = "apuser"` + "\n"
	config += `	dot1x_password = "Dot1xPass123!"` + "\n"
	config += `	dot1x_password_type = "clear"` + "\n"
	config += `	hyperlocation = false` + "\n"
	config += `	ip_dhcp_fallback = true` + "\n"
	config += `	lag = false` + "\n"
	config += `	led = true` + "\n"
	config += `	mesh_profile = "default-mesh-profile"` + "\n"
	config += `	rogue_detection_enable = true` + "\n"
	config += `	rogue_detection_min_rssi = -80` + "\n"
	config += `	rogue_detection_min_transient_time = 0` + "\n"
	config += `	rogue_detection_report_interval = 10` + "\n"
	config += `	statistics_ap_system_monitoring_enable = true` + "\n"
	config += `	statistics_ap_system_monitoring_alarm_enable = true` + "\n"
	config += `	statistics_ap_system_monitoring_alarm_hold_time = 6` + "\n"
	config += `	statistics_ap_system_monitoring_alarm_retransmit_time = 0` + "\n"
	config += `	statistics_ap_system_monitoring_cpu_threshold = 90` + "\n"
	config += `	statistics_ap_system_monitoring_mem_threshold = 90` + "\n"
	config += `	statistics_ap_system_monitoring_sampling_interval = 30` + "\n"
	config += `	statistics_ap_system_monitoring_stats_interval = 300` + "\n"
	config += `	statistics_traffic_distribution = true` + "\n"
	config += `	statistics_traffic_distribution_interval = 300` + "\n"
	config += `	statistics_ap_radio_monitoring_enable = false` + "\n"
	config += `	statistics_ap_radio_monitoring_sampling_interval = 720` + "\n"
	config += `	stats_timer = 180` + "\n"
	config += `	tcp_adjust_mss_enable = true` + "\n"
	config += `	tcp_adjust_mss_size = 1250` + "\n"
	config += `	ble_scan = false` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_wireless_ap_join_profile" "test" {
			name = "S3-AP-JOIN-1"
			depends_on = [iosxe_wireless_ap_join_profile.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
