// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeWirelessWLANProfile(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "wlan_id", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "ssid", "S1-CORP-PSK"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "wlan_status", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "broadcast_ssid", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "ccx_aironet_iesupport", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "peer_blocking", "p2p-blocking-action-drop"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_akm_dot1x", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_akm_ft_dot1x", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_akm_psk", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_akm_ft_psk", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_akm_sae", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_akm_ft_sae", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_wpa2_ciphers_aes", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_wpa3", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_psk_key_format", "key-ascii"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_wpa_psk_key_encryption", "clear"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_dot1x_authentication_list", ""))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_web_auth", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_web_auth_authentication_list", ""))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_web_auth_parameter_map", ""))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_ft", "dot11r-enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "security_ft_over_the_ds", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "mac_filtering", ""))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "load_balance", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_wlan_profile.test", "wmm", "apf-vap-wme-required"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeWirelessWLANProfileConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeWirelessWLANProfileConfig() string {
	config := `resource "iosxe_wireless_wlan_profile" "test" {` + "\n"
	config += `	profile_name = "S1-CORP-PSK"` + "\n"
	config += `	wlan_id = 10` + "\n"
	config += `	ssid = "S1-CORP-PSK"` + "\n"
	config += `	wlan_status = true` + "\n"
	config += `	broadcast_ssid = true` + "\n"
	config += `	ccx_aironet_iesupport = false` + "\n"
	config += `	peer_blocking = "p2p-blocking-action-drop"` + "\n"
	config += `	security_wpa_akm_dot1x = false` + "\n"
	config += `	security_wpa_akm_ft_dot1x = false` + "\n"
	config += `	security_wpa_akm_psk = true` + "\n"
	config += `	security_wpa_akm_ft_psk = true` + "\n"
	config += `	security_wpa_akm_sae = false` + "\n"
	config += `	security_wpa_akm_ft_sae = false` + "\n"
	config += `	security_wpa_wpa2_ciphers_aes = true` + "\n"
	config += `	security_wpa_wpa3 = false` + "\n"
	config += `	security_wpa_psk_key_format = "key-ascii"` + "\n"
	config += `	security_wpa_psk_key_encryption = "clear"` + "\n"
	config += `	security_wpa_psk_key = "Example-Passphrase-123"` + "\n"
	config += `	security_dot1x_authentication_list = ""` + "\n"
	config += `	security_web_auth = false` + "\n"
	config += `	security_web_auth_authentication_list = ""` + "\n"
	config += `	security_web_auth_parameter_map = ""` + "\n"
	config += `	security_ft = "dot11r-enabled"` + "\n"
	config += `	security_ft_over_the_ds = true` + "\n"
	config += `	mac_filtering = ""` + "\n"
	config += `	load_balance = true` + "\n"
	config += `	wmm = "apf-vap-wme-required"` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_wireless_wlan_profile" "test" {
			profile_name = "S1-CORP-PSK"
			depends_on = [iosxe_wireless_wlan_profile.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
