// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeWirelessPolicyProfile(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "description", "S2 Corporate users"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "status", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "vlan", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "aaa_override", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "nac", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "nac_type", "nac-support-radius"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "session_timeout", "3600"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "idle_timeout", "600"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "exclusionlist_timeout", "180"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "static_ip_mobility", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "dhcp_tlv_caching", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_wireless_policy_profile.test", "http_tlv_caching", "false"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeWirelessPolicyProfileConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeWirelessPolicyProfileConfig() string {
	config := `resource "iosxe_wireless_policy_profile" "test" {` + "\n"
	config += `	policy_profile_name = "S2-PP-CORP"` + "\n"
	config += `	description = "S2 Corporate users"` + "\n"
	config += `	status = true` + "\n"
	config += `	vlan = "100"` + "\n"
	config += `	aaa_override = true` + "\n"
	config += `	nac = true` + "\n"
	config += `	nac_type = "nac-support-radius"` + "\n"
	config += `	session_timeout = 3600` + "\n"
	config += `	idle_timeout = 600` + "\n"
	config += `	exclusionlist_timeout = 180` + "\n"
	config += `	static_ip_mobility = false` + "\n"
	config += `	dhcp_tlv_caching = false` + "\n"
	config += `	http_tlv_caching = false` + "\n"
	config += `	ipv4_flow_monitors_input = [{` + "\n"
	config += `	}]` + "\n"
	config += `	ipv4_flow_monitors_output = [{` + "\n"
	config += `	}]` + "\n"
	config += `	mobility_anchors = [{` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_wireless_policy_profile" "test" {
			policy_profile_name = "S2-PP-CORP"
			depends_on = [iosxe_wireless_policy_profile.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
