// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &WirelessAPJoinProfileDataSource{}
	_ datasource.DataSourceWithConfigure = &WirelessAPJoinProfileDataSource{}
)

func NewWirelessAPJoinProfileDataSource() datasource.DataSource {
	return &WirelessAPJoinProfileDataSource{}
}

type WirelessAPJoinProfileDataSource struct {
	data *IosxeProviderData
}

func (d *WirelessAPJoinProfileDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_ap_join_profile"
}

func (d *WirelessAPJoinProfileDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Wireless AP Join Profile configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The ap configuration profile name",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description for the ap configuration profile",
				Computed:            true,
			},
			"capwap_window_size": schema.Int64Attribute{
				MarkdownDescription: "CAPWAP window size for request packets in multiwindow queue",
				Computed:            true,
			},
			"country": schema.StringAttribute{
				MarkdownDescription: "AP country code",
				Computed:            true,
			},
			"ssh": schema.BoolAttribute{
				MarkdownDescription: "This object specifies whether SSH session can be established to the AP",
				Computed:            true,
			},
			"mgmtuser_username": schema.StringAttribute{
				MarkdownDescription: "AP user management username",
				Computed:            true,
			},
			"mgmtuser_password": schema.StringAttribute{
				MarkdownDescription: "AP user management password. Following criteria should be met if wireless password policy is configured. - Default passwords (cisco, Cisco, C!sco, ci$co, ..) are not allowed. - Reverse default passwords are not allowed. - At least one lower case letter is mandatory. - At least one upper case letter is mandatory. - At least one digit is mandatory. - Special characters are allowed, but not mandatory. - More than two sequential chars or digits (e.g., abc, 123) are not allowed. - More than two repeated chars or digits (e.g., 111, aaa) are not allowed. - Minimum password length is 8. Restriction: AP management password of cleartext type must contain ASCII characters only. This rule is not implemented using constraints.",
				Computed:            true,
			},
			"mgmtuser_password_type": schema.StringAttribute{
				MarkdownDescription: "AP user management password type",
				Computed:            true,
			},
			"mgmtuser_secret": schema.StringAttribute{
				MarkdownDescription: "AP user management secret",
				Computed:            true,
			},
			"mgmtuser_secret_type": schema.StringAttribute{
				MarkdownDescription: "AP user management secret type",
				Computed:            true,
			},
			"ntp_ip": schema.StringAttribute{
				MarkdownDescription: "NTP server IP address",
				Computed:            true,
			},
			"syslog_host": schema.StringAttribute{
				MarkdownDescription: "host name",
				Computed:            true,
			},
			"syslog_facility": schema.StringAttribute{
				MarkdownDescription: "facility value",
				Computed:            true,
			},
			"syslog_level": schema.StringAttribute{
				MarkdownDescription: "log level",
				Computed:            true,
			},
			"apphost": schema.BoolAttribute{
				MarkdownDescription: "Enable IOX application hosting",
				Computed:            true,
			},
			"association_limit": schema.Int64Attribute{
				MarkdownDescription: "Maximum clients per AP configuration",
				Computed:            true,
			},
			"awips": schema.BoolAttribute{
				MarkdownDescription: "Flag to enable AWIPS",
				Computed:            true,
			},
			"awips_forensic": schema.BoolAttribute{
				MarkdownDescription: "Flag to enable AWIPS forensic",
				Computed:            true,
			},
			"capwap_retransmit_count": schema.Int64Attribute{
				MarkdownDescription: "retransmit timer count",
				Computed:            true,
			},
			"capwap_retransmit_interval": schema.Int64Attribute{
				MarkdownDescription: "retransmit timer interval",
				Computed:            true,
			},
			"capwap_timers_discovery_timeout": schema.Int64Attribute{
				MarkdownDescription: "This object represents the timeout for the AP discovery",
				Computed:            true,
			},
			"capwap_timers_fast_heartbeat_timeout": schema.Int64Attribute{
				MarkdownDescription: "This object represents the timeout value for the heart beat timer.",
				Computed:            true,
			},
			"capwap_timers_heartbeat_timeout": schema.Int64Attribute{
				MarkdownDescription: "This object represents the Heartbeattimeout for the AP discovery",
				Computed:            true,
			},
			"capwap_timers_primary_discovery_timeout": schema.Int64Attribute{
				MarkdownDescription: "This object represents the timeout for the primary AP discovery",
				Computed:            true,
			},
			"capwap_timers_primed_join_timeout": schema.Int64Attribute{
				MarkdownDescription: "This object represents the primed timeout for the AP discovery",
				Computed:            true,
			},
			"capwap_backup_primary_name": schema.StringAttribute{
				MarkdownDescription: "the AP's primary controller name",
				Computed:            true,
			},
			"capwap_backup_primary_ip": schema.StringAttribute{
				MarkdownDescription: "the AP's primary controller ip address",
				Computed:            true,
			},
			"capwap_backup_secondary_name": schema.StringAttribute{
				MarkdownDescription: "the AP's secondary controller name",
				Computed:            true,
			},
			"capwap_backup_secondary_ip": schema.StringAttribute{
				MarkdownDescription: "the AP's secondary controller ip address",
				Computed:            true,
			},
			"capwap_fallback": schema.BoolAttribute{
				MarkdownDescription: "Backup Controllers fallback enabled",
				Computed:            true,
			},
			"capwap_discovery_private": schema.BoolAttribute{
				MarkdownDescription: "Discovery Response from private IP is enabled or disabled",
				Computed:            true,
			},
			"capwap_discovery_public": schema.BoolAttribute{
				MarkdownDescription: "Discovery Response from public IP is enabled or disabled",
				Computed:            true,
			},
			"cdp": schema.BoolAttribute{
				MarkdownDescription: "True if CDP enabled for the AP",
				Computed:            true,
			},
			"dot1x_eap_type": schema.StringAttribute{
				MarkdownDescription: "Dot1x EAP auth type",
				Computed:            true,
			},
			"dot1x_username": schema.StringAttribute{
				MarkdownDescription: "AP dot1x authentication username",
				Computed:            true,
			},
			"dot1x_password": schema.StringAttribute{
				MarkdownDescription: "AP dot1x authentication password",
				Computed:            true,
			},
			"dot1x_password_type": schema.StringAttribute{
				MarkdownDescription: "AP dot1x authentication password type",
				Computed:            true,
			},
			"hyperlocation": schema.BoolAttribute{
				MarkdownDescription: "enable hyperlocation",
				Computed:            true,
			},
			"ip_dhcp_fallback": schema.BoolAttribute{
				MarkdownDescription: "Represents AP fallback to DHCP, if AP fails to join via static IP address",
				Computed:            true,
			},
			"lag": schema.BoolAttribute{
				MarkdownDescription: "boolean to indicate whether ap lag enabled is used",
				Computed:            true,
			},
			"led": schema.BoolAttribute{
				MarkdownDescription: "True if LED state is enabled otherwise disabled.",
				Computed:            true,
			},
			"mesh_profile": schema.StringAttribute{
				MarkdownDescription: "Specifies the mesh profile name for the AP",
				Computed:            true,
			},
			"rogue_detection_enable": schema.BoolAttribute{
				MarkdownDescription: "rogue AP detection",
				Computed:            true,
			},
			"rogue_detection_min_rssi": schema.Int64Attribute{
				MarkdownDescription: "minmum RSSI for AP rogue detection",
				Computed:            true,
			},
			"rogue_detection_min_transient_time": schema.Int64Attribute{
				MarkdownDescription: "transient interval for AP rogue detection",
				Computed:            true,
			},
			"rogue_detection_report_interval": schema.Int64Attribute{
				MarkdownDescription: "time interval at which monitor mode report for AP rogue detection is generated",
				Computed:            true,
			},
			"statistics_ap_system_monitoring_enable": schema.BoolAttribute{
				MarkdownDescription: "AP stats collection and processing enabled",
				Computed:            true,
			},
			"statistics_ap_system_monitoring_alarm_enable": schema.BoolAttribute{
				MarkdownDescription: "AP stats alarms enabled",
				Computed:            true,
			},
			"statistics_ap_system_monitoring_alarm_hold_time": schema.Int64Attribute{
				MarkdownDescription: "Alarm hold time",
				Computed:            true,
			},
			"statistics_ap_system_monitoring_alarm_retransmit_time": schema.Int64Attribute{
				MarkdownDescription: "Alarm trap retransmission time",
				Computed:            true,
			},
			"statistics_ap_system_monitoring_cpu_threshold": schema.Int64Attribute{
				MarkdownDescription: "CPU threshold",
				Computed:            true,
			},
			"statistics_ap_system_monitoring_mem_threshold": schema.Int64Attribute{
				MarkdownDescription: "Memory threshold",
				Computed:            true,
			},
			"statistics_ap_system_monitoring_sampling_interval": schema.Int64Attribute{
				MarkdownDescription: "Sampling interval",
				Computed:            true,
			},
			"statistics_ap_system_monitoring_stats_interval": schema.Int64Attribute{
				MarkdownDescription: "Statistics interval",
				Computed:            true,
			},
			"statistics_traffic_distribution": schema.BoolAttribute{
				MarkdownDescription: "Enable/Disable client traffic distribution stats",
				Computed:            true,
			},
			"statistics_traffic_distribution_interval": schema.Int64Attribute{
				MarkdownDescription: "Interval at which AP will send the statistics",
				Computed:            true,
			},
			"statistics_ap_radio_monitoring_enable": schema.BoolAttribute{
				MarkdownDescription: "AP radio stats collection and processing enabled",
				Computed:            true,
			},
			"statistics_ap_radio_monitoring_sampling_interval": schema.Int64Attribute{
				MarkdownDescription: "Sampling interval of radio statistics",
				Computed:            true,
			},
			"stats_timer": schema.Int64Attribute{
				MarkdownDescription: "APs stats timer",
				Computed:            true,
			},
			"tcp_adjust_mss_enable": schema.BoolAttribute{
				MarkdownDescription: "adjust mss",
				Computed:            true,
			},
			"tcp_adjust_mss_size": schema.Int64Attribute{
				MarkdownDescription: "This object represents the Global AP TCP MSS value",
				Computed:            true,
			},
			"ble_scan": schema.BoolAttribute{
				MarkdownDescription: "Set the BLE scan state",
				Computed:            true,
			},
		},
	}
}

func (d *WirelessAPJoinProfileDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *WirelessAPJoinProfileDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config WirelessAPJoinProfileData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
