// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &WirelessRFProfileDataSource{}
	_ datasource.DataSourceWithConfigure = &WirelessRFProfileDataSource{}
)

func NewWirelessRFProfileDataSource() datasource.DataSource {
	return &WirelessRFProfileDataSource{}
}

type WirelessRFProfileDataSource struct {
	data *IosxeProviderData
}

func (d *WirelessRFProfileDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_rf_profile"
}

func (d *WirelessRFProfileDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the retrieved object.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"band": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"status": schema.BoolAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_1m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_2m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_5_5m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_11m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_6m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_9m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_12m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_18m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_24m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_36m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_48m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"data_rate_54m": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"band_select_client_rssi": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"band_select_cycle_count": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"band_select_cycle_threshold": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"band_select_expire_dual_band": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"band_select_expire_suppression": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"dca_allowed_channels": schema.ListNestedAttribute{
				MarkdownDescription: "",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"channel": schema.Int64Attribute{
							MarkdownDescription: "",
							Computed:            true,
						},
					},
				},
			},
			"coverage_data_rssi_threshold": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"coverage_voice_rssi_threshold": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"coverage_level_global": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"load_balancing_window": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"load_balancing_denial": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"max_clients": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"tx_power_v1_threshold": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"tx_power_max": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"tx_power_min": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"trap_threshold_clients": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"trap_threshold_interference": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"trap_threshold_noise": schema.Int64Attribute{
				MarkdownDescription: "",
				Computed:            true,
			},
		},
	}
}

func (d *WirelessRFProfileDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *WirelessRFProfileDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config WirelessRFProfileData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString()))
		return
	}

	// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
	locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
	if locked {
		defer device.NetconfOpMutex.Unlock()
	}
	defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

	filter := helpers.GetXpathFilter(config.getXPath())
	res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", config.getPath(), err))
		return
	}

	config.fromBodyXML(ctx, res.Res)

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
