// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"reflect"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessPolicyTag struct {
	Device       types.String                    `tfsdk:"device"`
	Id           types.String                    `tfsdk:"id"`
	TagName      types.String                    `tfsdk:"tag_name"`
	Description  types.String                    `tfsdk:"description"`
	WlanPolicies []WirelessPolicyTagWlanPolicies `tfsdk:"wlan_policies"`
}
type WirelessPolicyTagWlanPolicies struct {
	WlanProfileName   types.String `tfsdk:"wlan_profile_name"`
	PolicyProfileName types.String `tfsdk:"policy_profile_name"`
}

type WirelessPolicyTagData struct {
	Device       types.String                        `tfsdk:"device"`
	Id           types.String                        `tfsdk:"id"`
	TagName      types.String                        `tfsdk:"tag_name"`
	Description  types.String                        `tfsdk:"description"`
	WlanPolicies []WirelessPolicyTagWlanPoliciesData `tfsdk:"wlan_policies"`
}
type WirelessPolicyTagWlanPoliciesData struct {
	WlanProfileName   types.String `tfsdk:"wlan_profile_name"`
	PolicyProfileName types.String `tfsdk:"policy_profile_name"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data WirelessPolicyTag) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/policy-list-entries/policy-list-entry=%s", url.QueryEscape(fmt.Sprintf("%v", data.TagName.ValueString())))
}

func (data WirelessPolicyTagData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/policy-list-entries/policy-list-entry=%s", url.QueryEscape(fmt.Sprintf("%v", data.TagName.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data WirelessPolicyTag) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/policy-list-entries/policy-list-entry[tag-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.TagName.ValueString()))
	return path
}

func (data WirelessPolicyTagData) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/policy-list-entries/policy-list-entry[tag-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.TagName.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data WirelessPolicyTag) toBodyXML(ctx context.Context, config WirelessPolicyTag) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data WirelessPolicyTag) addToBodyXML(ctx context.Context, config WirelessPolicyTag, body netconf.Body) netconf.Body {
	if !data.TagName.IsNull() && !data.TagName.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/tag-name", data.TagName.ValueString())
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/description", data.Description.ValueString())
	}
	if len(data.WlanPolicies) > 0 {
		for _, item := range data.WlanPolicies {
			cBody := netconf.Body{}
			if !item.WlanProfileName.IsNull() && !item.WlanProfileName.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "wlan-profile-name", item.WlanProfileName.ValueString())
			}
			if !item.PolicyProfileName.IsNull() && !item.PolicyProfileName.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "policy-profile-name", item.PolicyProfileName.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/wlan-policies/wlan-policy", cBody.Res())
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *WirelessPolicyTag) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/tag-name"); value.Exists() && !data.TagName.IsNull() {
		data.TagName = types.StringValue(value.String())
	} else {
		data.TagName = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	for i := range data.WlanPolicies {
		keys := [...]string{"wlan-profile-name"}
		keyValues := [...]string{data.WlanPolicies[i].WlanProfileName.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-policies/wlan-policy").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "wlan-profile-name"); value.Exists() && !data.WlanPolicies[i].WlanProfileName.IsNull() {
			data.WlanPolicies[i].WlanProfileName = types.StringValue(value.String())
		} else {
			data.WlanPolicies[i].WlanProfileName = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "policy-profile-name"); value.Exists() && !data.WlanPolicies[i].PolicyProfileName.IsNull() {
			data.WlanPolicies[i].PolicyProfileName = types.StringValue(value.String())
		} else {
			data.WlanPolicies[i].PolicyProfileName = types.StringNull()
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *WirelessPolicyTag) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-policies/wlan-policy"); value.Exists() {
		data.WlanPolicies = make([]WirelessPolicyTagWlanPolicies, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := WirelessPolicyTagWlanPolicies{}
			if cValue := helpers.GetFromXPath(v, "wlan-profile-name"); cValue.Exists() {
				item.WlanProfileName = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "policy-profile-name"); cValue.Exists() {
				item.PolicyProfileName = types.StringValue(cValue.String())
			}
			data.WlanPolicies = append(data.WlanPolicies, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *WirelessPolicyTagData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-policies/wlan-policy"); value.Exists() {
		data.WlanPolicies = make([]WirelessPolicyTagWlanPoliciesData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := WirelessPolicyTagWlanPoliciesData{}
			if cValue := helpers.GetFromXPath(v, "wlan-profile-name"); cValue.Exists() {
				item.WlanProfileName = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "policy-profile-name"); cValue.Exists() {
				item.PolicyProfileName = types.StringValue(cValue.String())
			}
			data.WlanPolicies = append(data.WlanPolicies, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *WirelessPolicyTag) addDeletedItemsXML(ctx context.Context, state WirelessPolicyTag, body string) string {
	b := netconf.NewBody(body)
	for i := range state.WlanPolicies {
		stateKeys := [...]string{"wlan-profile-name"}
		stateKeyValues := [...]string{state.WlanPolicies[i].WlanProfileName.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.WlanPolicies[i].WlanProfileName.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.WlanPolicies {
			found = true
			if state.WlanPolicies[i].WlanProfileName.ValueString() != data.WlanPolicies[j].WlanProfileName.ValueString() {
				found = false
			}
			if found {
				if !state.WlanPolicies[i].PolicyProfileName.IsNull() && data.WlanPolicies[j].PolicyProfileName.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/wlan-policies/wlan-policy%v/policy-profile-name", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/wlan-policies/wlan-policy%v", predicates))
		}
	}
	if !state.Description.IsNull() && data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *WirelessPolicyTag) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.WlanPolicies {
		keys := [...]string{"wlan-profile-name"}
		keyValues := [...]string{data.WlanPolicies[i].WlanProfileName.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/wlan-policies/wlan-policy%v", predicates))
	}
	if !data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
