// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessAPJoinProfile struct {
	Device                                          types.String `tfsdk:"device"`
	Id                                              types.String `tfsdk:"id"`
	Name                                            types.String `tfsdk:"name"`
	Description                                     types.String `tfsdk:"description"`
	CapwapWindowSize                                types.Int64  `tfsdk:"capwap_window_size"`
	Country                                         types.String `tfsdk:"country"`
	Ssh                                             types.Bool   `tfsdk:"ssh"`
	MgmtuserUsername                                types.String `tfsdk:"mgmtuser_username"`
	MgmtuserPassword                                types.String `tfsdk:"mgmtuser_password"`
	MgmtuserPasswordType                            types.String `tfsdk:"mgmtuser_password_type"`
	MgmtuserSecret                                  types.String `tfsdk:"mgmtuser_secret"`
	MgmtuserSecretType                              types.String `tfsdk:"mgmtuser_secret_type"`
	NtpIp                                           types.String `tfsdk:"ntp_ip"`
	SyslogHost                                      types.String `tfsdk:"syslog_host"`
	SyslogFacility                                  types.String `tfsdk:"syslog_facility"`
	SyslogLevel                                     types.String `tfsdk:"syslog_level"`
	Apphost                                         types.Bool   `tfsdk:"apphost"`
	AssociationLimit                                types.Int64  `tfsdk:"association_limit"`
	Awips                                           types.Bool   `tfsdk:"awips"`
	AwipsForensic                                   types.Bool   `tfsdk:"awips_forensic"`
	CapwapRetransmitCount                           types.Int64  `tfsdk:"capwap_retransmit_count"`
	CapwapRetransmitInterval                        types.Int64  `tfsdk:"capwap_retransmit_interval"`
	CapwapTimersDiscoveryTimeout                    types.Int64  `tfsdk:"capwap_timers_discovery_timeout"`
	CapwapTimersFastHeartbeatTimeout                types.Int64  `tfsdk:"capwap_timers_fast_heartbeat_timeout"`
	CapwapTimersHeartbeatTimeout                    types.Int64  `tfsdk:"capwap_timers_heartbeat_timeout"`
	CapwapTimersPrimaryDiscoveryTimeout             types.Int64  `tfsdk:"capwap_timers_primary_discovery_timeout"`
	CapwapTimersPrimedJoinTimeout                   types.Int64  `tfsdk:"capwap_timers_primed_join_timeout"`
	CapwapBackupPrimaryName                         types.String `tfsdk:"capwap_backup_primary_name"`
	CapwapBackupPrimaryIp                           types.String `tfsdk:"capwap_backup_primary_ip"`
	CapwapBackupSecondaryName                       types.String `tfsdk:"capwap_backup_secondary_name"`
	CapwapBackupSecondaryIp                         types.String `tfsdk:"capwap_backup_secondary_ip"`
	CapwapFallback                                  types.Bool   `tfsdk:"capwap_fallback"`
	CapwapDiscoveryPrivate                          types.Bool   `tfsdk:"capwap_discovery_private"`
	CapwapDiscoveryPublic                           types.Bool   `tfsdk:"capwap_discovery_public"`
	Cdp                                             types.Bool   `tfsdk:"cdp"`
	Dot1xEapType                                    types.String `tfsdk:"dot1x_eap_type"`
	Dot1xUsername                                   types.String `tfsdk:"dot1x_username"`
	Dot1xPassword                                   types.String `tfsdk:"dot1x_password"`
	Dot1xPasswordType                               types.String `tfsdk:"dot1x_password_type"`
	Hyperlocation                                   types.Bool   `tfsdk:"hyperlocation"`
	IpDhcpFallback                                  types.Bool   `tfsdk:"ip_dhcp_fallback"`
	Lag                                             types.Bool   `tfsdk:"lag"`
	Led                                             types.Bool   `tfsdk:"led"`
	MeshProfile                                     types.String `tfsdk:"mesh_profile"`
	RogueDetectionEnable                            types.Bool   `tfsdk:"rogue_detection_enable"`
	RogueDetectionMinRssi                           types.Int64  `tfsdk:"rogue_detection_min_rssi"`
	RogueDetectionMinTransientTime                  types.Int64  `tfsdk:"rogue_detection_min_transient_time"`
	RogueDetectionReportInterval                    types.Int64  `tfsdk:"rogue_detection_report_interval"`
	StatisticsApSystemMonitoringEnable              types.Bool   `tfsdk:"statistics_ap_system_monitoring_enable"`
	StatisticsApSystemMonitoringAlarmEnable         types.Bool   `tfsdk:"statistics_ap_system_monitoring_alarm_enable"`
	StatisticsApSystemMonitoringAlarmHoldTime       types.Int64  `tfsdk:"statistics_ap_system_monitoring_alarm_hold_time"`
	StatisticsApSystemMonitoringAlarmRetransmitTime types.Int64  `tfsdk:"statistics_ap_system_monitoring_alarm_retransmit_time"`
	StatisticsApSystemMonitoringCpuThreshold        types.Int64  `tfsdk:"statistics_ap_system_monitoring_cpu_threshold"`
	StatisticsApSystemMonitoringMemThreshold        types.Int64  `tfsdk:"statistics_ap_system_monitoring_mem_threshold"`
	StatisticsApSystemMonitoringSamplingInterval    types.Int64  `tfsdk:"statistics_ap_system_monitoring_sampling_interval"`
	StatisticsApSystemMonitoringStatsInterval       types.Int64  `tfsdk:"statistics_ap_system_monitoring_stats_interval"`
	StatisticsTrafficDistribution                   types.Bool   `tfsdk:"statistics_traffic_distribution"`
	StatisticsTrafficDistributionInterval           types.Int64  `tfsdk:"statistics_traffic_distribution_interval"`
	StatisticsApRadioMonitoringEnable               types.Bool   `tfsdk:"statistics_ap_radio_monitoring_enable"`
	StatisticsApRadioMonitoringSamplingInterval     types.Int64  `tfsdk:"statistics_ap_radio_monitoring_sampling_interval"`
	StatsTimer                                      types.Int64  `tfsdk:"stats_timer"`
	TcpAdjustMssEnable                              types.Bool   `tfsdk:"tcp_adjust_mss_enable"`
	TcpAdjustMssSize                                types.Int64  `tfsdk:"tcp_adjust_mss_size"`
	BleScan                                         types.Bool   `tfsdk:"ble_scan"`
}

type WirelessAPJoinProfileData struct {
	Device                                          types.String `tfsdk:"device"`
	Id                                              types.String `tfsdk:"id"`
	Name                                            types.String `tfsdk:"name"`
	Description                                     types.String `tfsdk:"description"`
	CapwapWindowSize                                types.Int64  `tfsdk:"capwap_window_size"`
	Country                                         types.String `tfsdk:"country"`
	Ssh                                             types.Bool   `tfsdk:"ssh"`
	MgmtuserUsername                                types.String `tfsdk:"mgmtuser_username"`
	MgmtuserPassword                                types.String `tfsdk:"mgmtuser_password"`
	MgmtuserPasswordType                            types.String `tfsdk:"mgmtuser_password_type"`
	MgmtuserSecret                                  types.String `tfsdk:"mgmtuser_secret"`
	MgmtuserSecretType                              types.String `tfsdk:"mgmtuser_secret_type"`
	NtpIp                                           types.String `tfsdk:"ntp_ip"`
	SyslogHost                                      types.String `tfsdk:"syslog_host"`
	SyslogFacility                                  types.String `tfsdk:"syslog_facility"`
	SyslogLevel                                     types.String `tfsdk:"syslog_level"`
	Apphost                                         types.Bool   `tfsdk:"apphost"`
	AssociationLimit                                types.Int64  `tfsdk:"association_limit"`
	Awips                                           types.Bool   `tfsdk:"awips"`
	AwipsForensic                                   types.Bool   `tfsdk:"awips_forensic"`
	CapwapRetransmitCount                           types.Int64  `tfsdk:"capwap_retransmit_count"`
	CapwapRetransmitInterval                        types.Int64  `tfsdk:"capwap_retransmit_interval"`
	CapwapTimersDiscoveryTimeout                    types.Int64  `tfsdk:"capwap_timers_discovery_timeout"`
	CapwapTimersFastHeartbeatTimeout                types.Int64  `tfsdk:"capwap_timers_fast_heartbeat_timeout"`
	CapwapTimersHeartbeatTimeout                    types.Int64  `tfsdk:"capwap_timers_heartbeat_timeout"`
	CapwapTimersPrimaryDiscoveryTimeout             types.Int64  `tfsdk:"capwap_timers_primary_discovery_timeout"`
	CapwapTimersPrimedJoinTimeout                   types.Int64  `tfsdk:"capwap_timers_primed_join_timeout"`
	CapwapBackupPrimaryName                         types.String `tfsdk:"capwap_backup_primary_name"`
	CapwapBackupPrimaryIp                           types.String `tfsdk:"capwap_backup_primary_ip"`
	CapwapBackupSecondaryName                       types.String `tfsdk:"capwap_backup_secondary_name"`
	CapwapBackupSecondaryIp                         types.String `tfsdk:"capwap_backup_secondary_ip"`
	CapwapFallback                                  types.Bool   `tfsdk:"capwap_fallback"`
	CapwapDiscoveryPrivate                          types.Bool   `tfsdk:"capwap_discovery_private"`
	CapwapDiscoveryPublic                           types.Bool   `tfsdk:"capwap_discovery_public"`
	Cdp                                             types.Bool   `tfsdk:"cdp"`
	Dot1xEapType                                    types.String `tfsdk:"dot1x_eap_type"`
	Dot1xUsername                                   types.String `tfsdk:"dot1x_username"`
	Dot1xPassword                                   types.String `tfsdk:"dot1x_password"`
	Dot1xPasswordType                               types.String `tfsdk:"dot1x_password_type"`
	Hyperlocation                                   types.Bool   `tfsdk:"hyperlocation"`
	IpDhcpFallback                                  types.Bool   `tfsdk:"ip_dhcp_fallback"`
	Lag                                             types.Bool   `tfsdk:"lag"`
	Led                                             types.Bool   `tfsdk:"led"`
	MeshProfile                                     types.String `tfsdk:"mesh_profile"`
	RogueDetectionEnable                            types.Bool   `tfsdk:"rogue_detection_enable"`
	RogueDetectionMinRssi                           types.Int64  `tfsdk:"rogue_detection_min_rssi"`
	RogueDetectionMinTransientTime                  types.Int64  `tfsdk:"rogue_detection_min_transient_time"`
	RogueDetectionReportInterval                    types.Int64  `tfsdk:"rogue_detection_report_interval"`
	StatisticsApSystemMonitoringEnable              types.Bool   `tfsdk:"statistics_ap_system_monitoring_enable"`
	StatisticsApSystemMonitoringAlarmEnable         types.Bool   `tfsdk:"statistics_ap_system_monitoring_alarm_enable"`
	StatisticsApSystemMonitoringAlarmHoldTime       types.Int64  `tfsdk:"statistics_ap_system_monitoring_alarm_hold_time"`
	StatisticsApSystemMonitoringAlarmRetransmitTime types.Int64  `tfsdk:"statistics_ap_system_monitoring_alarm_retransmit_time"`
	StatisticsApSystemMonitoringCpuThreshold        types.Int64  `tfsdk:"statistics_ap_system_monitoring_cpu_threshold"`
	StatisticsApSystemMonitoringMemThreshold        types.Int64  `tfsdk:"statistics_ap_system_monitoring_mem_threshold"`
	StatisticsApSystemMonitoringSamplingInterval    types.Int64  `tfsdk:"statistics_ap_system_monitoring_sampling_interval"`
	StatisticsApSystemMonitoringStatsInterval       types.Int64  `tfsdk:"statistics_ap_system_monitoring_stats_interval"`
	StatisticsTrafficDistribution                   types.Bool   `tfsdk:"statistics_traffic_distribution"`
	StatisticsTrafficDistributionInterval           types.Int64  `tfsdk:"statistics_traffic_distribution_interval"`
	StatisticsApRadioMonitoringEnable               types.Bool   `tfsdk:"statistics_ap_radio_monitoring_enable"`
	StatisticsApRadioMonitoringSamplingInterval     types.Int64  `tfsdk:"statistics_ap_radio_monitoring_sampling_interval"`
	StatsTimer                                      types.Int64  `tfsdk:"stats_timer"`
	TcpAdjustMssEnable                              types.Bool   `tfsdk:"tcp_adjust_mss_enable"`
	TcpAdjustMssSize                                types.Int64  `tfsdk:"tcp_adjust_mss_size"`
	BleScan                                         types.Bool   `tfsdk:"ble_scan"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data WirelessAPJoinProfile) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-site-cfg:site-cfg-data/ap-cfg-profiles/ap-cfg-profile=%s", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

func (data WirelessAPJoinProfileData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-site-cfg:site-cfg-data/ap-cfg-profiles/ap-cfg-profile=%s", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data WirelessAPJoinProfile) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-site-cfg:site-cfg-data/ap-cfg-profiles/ap-cfg-profile[profile-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Name.ValueString()))
	return path
}

func (data WirelessAPJoinProfileData) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-site-cfg:site-cfg-data/ap-cfg-profiles/ap-cfg-profile[profile-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Name.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data WirelessAPJoinProfile) toBodyXML(ctx context.Context, config WirelessAPJoinProfile) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data WirelessAPJoinProfile) addToBodyXML(ctx context.Context, config WirelessAPJoinProfile, body netconf.Body) netconf.Body {
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/profile-name", data.Name.ValueString())
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/description", data.Description.ValueString())
	}
	if !data.CapwapWindowSize.IsNull() && !data.CapwapWindowSize.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/capwap-window/window-size", strconv.FormatInt(data.CapwapWindowSize.ValueInt64(), 10))
	}
	if !data.Country.IsNull() && !data.Country.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/ap-country/country-code", data.Country.ValueString())
	}
	if !data.Ssh.IsNull() && !data.Ssh.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/device-mgmt/ssh", data.Ssh.ValueBool())
	}
	if !data.MgmtuserUsername.IsNull() && !data.MgmtuserUsername.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/user-mgmt/username", data.MgmtuserUsername.ValueString())
	}
	if !data.MgmtuserPassword.IsNull() && !data.MgmtuserPassword.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/user-mgmt/password", data.MgmtuserPassword.ValueString())
	}
	if !data.MgmtuserPasswordType.IsNull() && !data.MgmtuserPasswordType.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/user-mgmt/password-type", data.MgmtuserPasswordType.ValueString())
	}
	if !data.MgmtuserSecret.IsNull() && !data.MgmtuserSecret.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/user-mgmt/secret", data.MgmtuserSecret.ValueString())
	}
	if !data.MgmtuserSecretType.IsNull() && !data.MgmtuserSecretType.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/user-mgmt/secret-type", data.MgmtuserSecretType.ValueString())
	}
	if !data.NtpIp.IsNull() && !data.NtpIp.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/ntp-server-info/ntp-address", data.NtpIp.ValueString())
	}
	if !data.SyslogHost.IsNull() && !data.SyslogHost.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/syslog/host", data.SyslogHost.ValueString())
	}
	if !data.SyslogFacility.IsNull() && !data.SyslogFacility.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/syslog/facility-value", data.SyslogFacility.ValueString())
	}
	if !data.SyslogLevel.IsNull() && !data.SyslogLevel.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/syslog/log-level", data.SyslogLevel.ValueString())
	}
	if !data.Apphost.IsNull() && !data.Apphost.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/apphost/enable", data.Apphost.ValueBool())
	}
	if !data.AssociationLimit.IsNull() && !data.AssociationLimit.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/client-limit/max-cfg-clients", strconv.FormatInt(data.AssociationLimit.ValueInt64(), 10))
	}
	if !data.Awips.IsNull() && !data.Awips.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/awips-enabled", data.Awips.ValueBool())
	}
	if !data.AwipsForensic.IsNull() && !data.AwipsForensic.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/awips-forensic-enabled", data.AwipsForensic.ValueBool())
	}
	if !data.CapwapRetransmitCount.IsNull() && !data.CapwapRetransmitCount.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/retransmit-timer/count", strconv.FormatInt(data.CapwapRetransmitCount.ValueInt64(), 10))
	}
	if !data.CapwapRetransmitInterval.IsNull() && !data.CapwapRetransmitInterval.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/retransmit-timer/interval", strconv.FormatInt(data.CapwapRetransmitInterval.ValueInt64(), 10))
	}
	if !data.CapwapTimersDiscoveryTimeout.IsNull() && !data.CapwapTimersDiscoveryTimeout.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/capwap-timer/discovery-timeout", strconv.FormatInt(data.CapwapTimersDiscoveryTimeout.ValueInt64(), 10))
	}
	if !data.CapwapTimersFastHeartbeatTimeout.IsNull() && !data.CapwapTimersFastHeartbeatTimeout.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/capwap-timer/fast-heart-beat-timeout", strconv.FormatInt(data.CapwapTimersFastHeartbeatTimeout.ValueInt64(), 10))
	}
	if !data.CapwapTimersHeartbeatTimeout.IsNull() && !data.CapwapTimersHeartbeatTimeout.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/capwap-timer/heart-beat-timeout", strconv.FormatInt(data.CapwapTimersHeartbeatTimeout.ValueInt64(), 10))
	}
	if !data.CapwapTimersPrimaryDiscoveryTimeout.IsNull() && !data.CapwapTimersPrimaryDiscoveryTimeout.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/capwap-timer/primary-discovery-timeout", strconv.FormatInt(data.CapwapTimersPrimaryDiscoveryTimeout.ValueInt64(), 10))
	}
	if !data.CapwapTimersPrimedJoinTimeout.IsNull() && !data.CapwapTimersPrimedJoinTimeout.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/capwap-timer/primed-join-timeout", strconv.FormatInt(data.CapwapTimersPrimedJoinTimeout.ValueInt64(), 10))
	}
	if !data.CapwapBackupPrimaryName.IsNull() && !data.CapwapBackupPrimaryName.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/backup-controllers/primary-controller-name", data.CapwapBackupPrimaryName.ValueString())
	}
	if !data.CapwapBackupPrimaryIp.IsNull() && !data.CapwapBackupPrimaryIp.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/backup-controllers/primary-controller-ip", data.CapwapBackupPrimaryIp.ValueString())
	}
	if !data.CapwapBackupSecondaryName.IsNull() && !data.CapwapBackupSecondaryName.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/backup-controllers/secondary-controller-name", data.CapwapBackupSecondaryName.ValueString())
	}
	if !data.CapwapBackupSecondaryIp.IsNull() && !data.CapwapBackupSecondaryIp.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/backup-controllers/secondary-controller-ip", data.CapwapBackupSecondaryIp.ValueString())
	}
	if !data.CapwapFallback.IsNull() && !data.CapwapFallback.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/backup-controllers/fallback-enabled", data.CapwapFallback.ValueBool())
	}
	if !data.CapwapDiscoveryPrivate.IsNull() && !data.CapwapDiscoveryPrivate.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/private-ip-discovery", data.CapwapDiscoveryPrivate.ValueBool())
	}
	if !data.CapwapDiscoveryPublic.IsNull() && !data.CapwapDiscoveryPublic.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/public-ip-discovery", data.CapwapDiscoveryPublic.ValueBool())
	}
	if !data.Cdp.IsNull() && !data.Cdp.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/cdp/cdp-enable", data.Cdp.ValueBool())
	}
	if !data.Dot1xEapType.IsNull() && !data.Dot1xEapType.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/dot1x-eap-type-info/dot1x-eap-type", data.Dot1xEapType.ValueString())
	}
	if !data.Dot1xUsername.IsNull() && !data.Dot1xUsername.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/login-credentials/dot1x-username", data.Dot1xUsername.ValueString())
	}
	if !data.Dot1xPassword.IsNull() && !data.Dot1xPassword.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/login-credentials/dot1x-password", data.Dot1xPassword.ValueString())
	}
	if !data.Dot1xPasswordType.IsNull() && !data.Dot1xPasswordType.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/login-credentials/dot1x-password-type", data.Dot1xPasswordType.ValueString())
	}
	if !data.Hyperlocation.IsNull() && !data.Hyperlocation.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/hyperlocation/hyperlocation-enable", data.Hyperlocation.ValueBool())
	}
	if !data.IpDhcpFallback.IsNull() && !data.IpDhcpFallback.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/dhcp-fallback/dhcp-fallback", data.IpDhcpFallback.ValueBool())
	}
	if !data.Lag.IsNull() && !data.Lag.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/lag-info/ap-lag-enabled", data.Lag.ValueBool())
	}
	if !data.Led.IsNull() && !data.Led.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/led-state/led-state", data.Led.ValueBool())
	}
	if !data.MeshProfile.IsNull() && !data.MeshProfile.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/mesh/mesh-profile-name", data.MeshProfile.ValueString())
	}
	if !data.RogueDetectionEnable.IsNull() && !data.RogueDetectionEnable.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/rogue-detection/ap-rogue-detection", data.RogueDetectionEnable.ValueBool())
	}
	if !data.RogueDetectionMinRssi.IsNull() && !data.RogueDetectionMinRssi.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/rogue-detection/ap-rogue-detection-min-rssi", strconv.FormatInt(data.RogueDetectionMinRssi.ValueInt64(), 10))
	}
	if !data.RogueDetectionMinTransientTime.IsNull() && !data.RogueDetectionMinTransientTime.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/rogue-detection/ap-rogue-detection-transient-interval", strconv.FormatInt(data.RogueDetectionMinTransientTime.ValueInt64(), 10))
	}
	if !data.RogueDetectionReportInterval.IsNull() && !data.RogueDetectionReportInterval.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/rogue-detection/rogue-detection-monitor-mode-report-interval", strconv.FormatInt(data.RogueDetectionReportInterval.ValueInt64(), 10))
	}
	if !data.StatisticsApSystemMonitoringEnable.IsNull() && !data.StatisticsApSystemMonitoringEnable.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/stats-monitor/enable", data.StatisticsApSystemMonitoringEnable.ValueBool())
	}
	if !data.StatisticsApSystemMonitoringAlarmEnable.IsNull() && !data.StatisticsApSystemMonitoringAlarmEnable.IsUnknown() {
		if data.StatisticsApSystemMonitoringAlarmEnable.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/stats-monitor/alarms-enable", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/stats-monitor/alarms-enable")
		}
	}
	if !data.StatisticsApSystemMonitoringAlarmHoldTime.IsNull() && !data.StatisticsApSystemMonitoringAlarmHoldTime.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/stats-monitor/alarm-hold-time", strconv.FormatInt(data.StatisticsApSystemMonitoringAlarmHoldTime.ValueInt64(), 10))
	}
	if !data.StatisticsApSystemMonitoringAlarmRetransmitTime.IsNull() && !data.StatisticsApSystemMonitoringAlarmRetransmitTime.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/stats-monitor/trap-retx-time", strconv.FormatInt(data.StatisticsApSystemMonitoringAlarmRetransmitTime.ValueInt64(), 10))
	}
	if !data.StatisticsApSystemMonitoringCpuThreshold.IsNull() && !data.StatisticsApSystemMonitoringCpuThreshold.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/stats-monitor/cpu-threshold", strconv.FormatInt(data.StatisticsApSystemMonitoringCpuThreshold.ValueInt64(), 10))
	}
	if !data.StatisticsApSystemMonitoringMemThreshold.IsNull() && !data.StatisticsApSystemMonitoringMemThreshold.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/stats-monitor/mem-threshold", strconv.FormatInt(data.StatisticsApSystemMonitoringMemThreshold.ValueInt64(), 10))
	}
	if !data.StatisticsApSystemMonitoringSamplingInterval.IsNull() && !data.StatisticsApSystemMonitoringSamplingInterval.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/stats-monitor/sample-intvl", strconv.FormatInt(data.StatisticsApSystemMonitoringSamplingInterval.ValueInt64(), 10))
	}
	if !data.StatisticsApSystemMonitoringStatsInterval.IsNull() && !data.StatisticsApSystemMonitoringStatsInterval.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/stats-monitor/stats-intvl", strconv.FormatInt(data.StatisticsApSystemMonitoringStatsInterval.ValueInt64(), 10))
	}
	if !data.StatisticsTrafficDistribution.IsNull() && !data.StatisticsTrafficDistribution.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/traffic-distribution/status", data.StatisticsTrafficDistribution.ValueBool())
	}
	if !data.StatisticsTrafficDistributionInterval.IsNull() && !data.StatisticsTrafficDistributionInterval.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/traffic-distribution/interval", strconv.FormatInt(data.StatisticsTrafficDistributionInterval.ValueInt64(), 10))
	}
	if !data.StatisticsApRadioMonitoringEnable.IsNull() && !data.StatisticsApRadioMonitoringEnable.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/radio-stats-monitor/enable", data.StatisticsApRadioMonitoringEnable.ValueBool())
	}
	if !data.StatisticsApRadioMonitoringSamplingInterval.IsNull() && !data.StatisticsApRadioMonitoringSamplingInterval.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/radio-stats-monitor/sample-intvl", strconv.FormatInt(data.StatisticsApRadioMonitoringSamplingInterval.ValueInt64(), 10))
	}
	if !data.StatsTimer.IsNull() && !data.StatsTimer.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/stats-timer/stats-timer", strconv.FormatInt(data.StatsTimer.ValueInt64(), 10))
	}
	if !data.TcpAdjustMssEnable.IsNull() && !data.TcpAdjustMssEnable.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/tcp-mss/adjust-mss", data.TcpAdjustMssEnable.ValueBool())
	}
	if !data.TcpAdjustMssSize.IsNull() && !data.TcpAdjustMssSize.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/tcp-mss/tcp-adjust-mss", strconv.FormatInt(data.TcpAdjustMssSize.ValueInt64(), 10))
	}
	if !data.BleScan.IsNull() && !data.BleScan.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/ble/scan-state", data.BleScan.ValueBool())
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *WirelessAPJoinProfile) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/profile-name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-window/window-size"); value.Exists() && !data.CapwapWindowSize.IsNull() {
		data.CapwapWindowSize = types.Int64Value(value.Int())
	} else {
		data.CapwapWindowSize = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ap-country/country-code"); value.Exists() && !data.Country.IsNull() {
		data.Country = types.StringValue(value.String())
	} else {
		data.Country = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/device-mgmt/ssh"); !data.Ssh.IsNull() {
		if value.Exists() {
			data.Ssh = types.BoolValue(value.Bool())
		}
	} else {
		data.Ssh = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/username"); value.Exists() && !data.MgmtuserUsername.IsNull() {
		data.MgmtuserUsername = types.StringValue(value.String())
	} else {
		data.MgmtuserUsername = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/password-type"); value.Exists() && !data.MgmtuserPasswordType.IsNull() {
		data.MgmtuserPasswordType = types.StringValue(value.String())
	} else {
		data.MgmtuserPasswordType = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/secret-type"); value.Exists() && !data.MgmtuserSecretType.IsNull() {
		data.MgmtuserSecretType = types.StringValue(value.String())
	} else {
		data.MgmtuserSecretType = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ntp-server-info/ntp-address"); value.Exists() && !data.NtpIp.IsNull() {
		data.NtpIp = types.StringValue(value.String())
	} else {
		data.NtpIp = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/host"); value.Exists() && !data.SyslogHost.IsNull() {
		data.SyslogHost = types.StringValue(value.String())
	} else {
		data.SyslogHost = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/facility-value"); value.Exists() && !data.SyslogFacility.IsNull() {
		data.SyslogFacility = types.StringValue(value.String())
	} else {
		data.SyslogFacility = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/log-level"); value.Exists() && !data.SyslogLevel.IsNull() {
		data.SyslogLevel = types.StringValue(value.String())
	} else {
		data.SyslogLevel = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apphost/enable"); !data.Apphost.IsNull() {
		if value.Exists() {
			data.Apphost = types.BoolValue(value.Bool())
		}
	} else {
		data.Apphost = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/client-limit/max-cfg-clients"); value.Exists() && !data.AssociationLimit.IsNull() {
		data.AssociationLimit = types.Int64Value(value.Int())
	} else {
		data.AssociationLimit = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/awips-enabled"); !data.Awips.IsNull() {
		if value.Exists() {
			data.Awips = types.BoolValue(value.Bool())
		}
	} else {
		data.Awips = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/awips-forensic-enabled"); !data.AwipsForensic.IsNull() {
		if value.Exists() {
			data.AwipsForensic = types.BoolValue(value.Bool())
		}
	} else {
		data.AwipsForensic = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/retransmit-timer/count"); value.Exists() && !data.CapwapRetransmitCount.IsNull() {
		data.CapwapRetransmitCount = types.Int64Value(value.Int())
	} else {
		data.CapwapRetransmitCount = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/retransmit-timer/interval"); value.Exists() && !data.CapwapRetransmitInterval.IsNull() {
		data.CapwapRetransmitInterval = types.Int64Value(value.Int())
	} else {
		data.CapwapRetransmitInterval = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/discovery-timeout"); value.Exists() && !data.CapwapTimersDiscoveryTimeout.IsNull() {
		data.CapwapTimersDiscoveryTimeout = types.Int64Value(value.Int())
	} else {
		data.CapwapTimersDiscoveryTimeout = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/fast-heart-beat-timeout"); value.Exists() && !data.CapwapTimersFastHeartbeatTimeout.IsNull() {
		data.CapwapTimersFastHeartbeatTimeout = types.Int64Value(value.Int())
	} else {
		data.CapwapTimersFastHeartbeatTimeout = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/heart-beat-timeout"); value.Exists() && !data.CapwapTimersHeartbeatTimeout.IsNull() {
		data.CapwapTimersHeartbeatTimeout = types.Int64Value(value.Int())
	} else {
		data.CapwapTimersHeartbeatTimeout = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/primary-discovery-timeout"); value.Exists() && !data.CapwapTimersPrimaryDiscoveryTimeout.IsNull() {
		data.CapwapTimersPrimaryDiscoveryTimeout = types.Int64Value(value.Int())
	} else {
		data.CapwapTimersPrimaryDiscoveryTimeout = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/primed-join-timeout"); value.Exists() && !data.CapwapTimersPrimedJoinTimeout.IsNull() {
		data.CapwapTimersPrimedJoinTimeout = types.Int64Value(value.Int())
	} else {
		data.CapwapTimersPrimedJoinTimeout = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/primary-controller-name"); value.Exists() && !data.CapwapBackupPrimaryName.IsNull() {
		data.CapwapBackupPrimaryName = types.StringValue(value.String())
	} else {
		data.CapwapBackupPrimaryName = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/primary-controller-ip"); value.Exists() && !data.CapwapBackupPrimaryIp.IsNull() {
		data.CapwapBackupPrimaryIp = types.StringValue(value.String())
	} else {
		data.CapwapBackupPrimaryIp = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/secondary-controller-name"); value.Exists() && !data.CapwapBackupSecondaryName.IsNull() {
		data.CapwapBackupSecondaryName = types.StringValue(value.String())
	} else {
		data.CapwapBackupSecondaryName = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/secondary-controller-ip"); value.Exists() && !data.CapwapBackupSecondaryIp.IsNull() {
		data.CapwapBackupSecondaryIp = types.StringValue(value.String())
	} else {
		data.CapwapBackupSecondaryIp = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/fallback-enabled"); !data.CapwapFallback.IsNull() {
		if value.Exists() {
			data.CapwapFallback = types.BoolValue(value.Bool())
		}
	} else {
		data.CapwapFallback = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/private-ip-discovery"); !data.CapwapDiscoveryPrivate.IsNull() {
		if value.Exists() {
			data.CapwapDiscoveryPrivate = types.BoolValue(value.Bool())
		}
	} else {
		data.CapwapDiscoveryPrivate = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/public-ip-discovery"); !data.CapwapDiscoveryPublic.IsNull() {
		if value.Exists() {
			data.CapwapDiscoveryPublic = types.BoolValue(value.Bool())
		}
	} else {
		data.CapwapDiscoveryPublic = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/cdp/cdp-enable"); !data.Cdp.IsNull() {
		if value.Exists() {
			data.Cdp = types.BoolValue(value.Bool())
		}
	} else {
		data.Cdp = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dot1x-eap-type-info/dot1x-eap-type"); value.Exists() && !data.Dot1xEapType.IsNull() {
		data.Dot1xEapType = types.StringValue(value.String())
	} else {
		data.Dot1xEapType = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login-credentials/dot1x-username"); value.Exists() && !data.Dot1xUsername.IsNull() {
		data.Dot1xUsername = types.StringValue(value.String())
	} else {
		data.Dot1xUsername = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login-credentials/dot1x-password-type"); value.Exists() && !data.Dot1xPasswordType.IsNull() {
		data.Dot1xPasswordType = types.StringValue(value.String())
	} else {
		data.Dot1xPasswordType = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hyperlocation/hyperlocation-enable"); !data.Hyperlocation.IsNull() {
		if value.Exists() {
			data.Hyperlocation = types.BoolValue(value.Bool())
		}
	} else {
		data.Hyperlocation = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dhcp-fallback/dhcp-fallback"); !data.IpDhcpFallback.IsNull() {
		if value.Exists() {
			data.IpDhcpFallback = types.BoolValue(value.Bool())
		}
	} else {
		data.IpDhcpFallback = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lag-info/ap-lag-enabled"); !data.Lag.IsNull() {
		if value.Exists() {
			data.Lag = types.BoolValue(value.Bool())
		}
	} else {
		data.Lag = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/led-state/led-state"); !data.Led.IsNull() {
		if value.Exists() {
			data.Led = types.BoolValue(value.Bool())
		}
	} else {
		data.Led = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/mesh/mesh-profile-name"); value.Exists() && !data.MeshProfile.IsNull() {
		data.MeshProfile = types.StringValue(value.String())
	} else {
		data.MeshProfile = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection"); !data.RogueDetectionEnable.IsNull() {
		if value.Exists() {
			data.RogueDetectionEnable = types.BoolValue(value.Bool())
		}
	} else {
		data.RogueDetectionEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection-min-rssi"); value.Exists() && !data.RogueDetectionMinRssi.IsNull() {
		data.RogueDetectionMinRssi = types.Int64Value(value.Int())
	} else {
		data.RogueDetectionMinRssi = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection-transient-interval"); value.Exists() && !data.RogueDetectionMinTransientTime.IsNull() {
		data.RogueDetectionMinTransientTime = types.Int64Value(value.Int())
	} else {
		data.RogueDetectionMinTransientTime = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/rogue-detection-monitor-mode-report-interval"); value.Exists() && !data.RogueDetectionReportInterval.IsNull() {
		data.RogueDetectionReportInterval = types.Int64Value(value.Int())
	} else {
		data.RogueDetectionReportInterval = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/enable"); !data.StatisticsApSystemMonitoringEnable.IsNull() {
		if value.Exists() {
			data.StatisticsApSystemMonitoringEnable = types.BoolValue(value.Bool())
		}
	} else {
		data.StatisticsApSystemMonitoringEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/alarms-enable"); !data.StatisticsApSystemMonitoringAlarmEnable.IsNull() {
		if value.Exists() {
			data.StatisticsApSystemMonitoringAlarmEnable = types.BoolValue(true)
		} else {
			data.StatisticsApSystemMonitoringAlarmEnable = types.BoolValue(false)
		}
	} else {
		data.StatisticsApSystemMonitoringAlarmEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/alarm-hold-time"); value.Exists() && !data.StatisticsApSystemMonitoringAlarmHoldTime.IsNull() {
		data.StatisticsApSystemMonitoringAlarmHoldTime = types.Int64Value(value.Int())
	} else {
		data.StatisticsApSystemMonitoringAlarmHoldTime = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/trap-retx-time"); value.Exists() && !data.StatisticsApSystemMonitoringAlarmRetransmitTime.IsNull() {
		data.StatisticsApSystemMonitoringAlarmRetransmitTime = types.Int64Value(value.Int())
	} else {
		data.StatisticsApSystemMonitoringAlarmRetransmitTime = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/cpu-threshold"); value.Exists() && !data.StatisticsApSystemMonitoringCpuThreshold.IsNull() {
		data.StatisticsApSystemMonitoringCpuThreshold = types.Int64Value(value.Int())
	} else {
		data.StatisticsApSystemMonitoringCpuThreshold = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/mem-threshold"); value.Exists() && !data.StatisticsApSystemMonitoringMemThreshold.IsNull() {
		data.StatisticsApSystemMonitoringMemThreshold = types.Int64Value(value.Int())
	} else {
		data.StatisticsApSystemMonitoringMemThreshold = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/sample-intvl"); value.Exists() && !data.StatisticsApSystemMonitoringSamplingInterval.IsNull() {
		data.StatisticsApSystemMonitoringSamplingInterval = types.Int64Value(value.Int())
	} else {
		data.StatisticsApSystemMonitoringSamplingInterval = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/stats-intvl"); value.Exists() && !data.StatisticsApSystemMonitoringStatsInterval.IsNull() {
		data.StatisticsApSystemMonitoringStatsInterval = types.Int64Value(value.Int())
	} else {
		data.StatisticsApSystemMonitoringStatsInterval = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/traffic-distribution/status"); !data.StatisticsTrafficDistribution.IsNull() {
		if value.Exists() {
			data.StatisticsTrafficDistribution = types.BoolValue(value.Bool())
		}
	} else {
		data.StatisticsTrafficDistribution = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/traffic-distribution/interval"); value.Exists() && !data.StatisticsTrafficDistributionInterval.IsNull() {
		data.StatisticsTrafficDistributionInterval = types.Int64Value(value.Int())
	} else {
		data.StatisticsTrafficDistributionInterval = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/radio-stats-monitor/enable"); !data.StatisticsApRadioMonitoringEnable.IsNull() {
		if value.Exists() {
			data.StatisticsApRadioMonitoringEnable = types.BoolValue(value.Bool())
		}
	} else {
		data.StatisticsApRadioMonitoringEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/radio-stats-monitor/sample-intvl"); value.Exists() && !data.StatisticsApRadioMonitoringSamplingInterval.IsNull() {
		data.StatisticsApRadioMonitoringSamplingInterval = types.Int64Value(value.Int())
	} else {
		data.StatisticsApRadioMonitoringSamplingInterval = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-timer/stats-timer"); value.Exists() && !data.StatsTimer.IsNull() {
		data.StatsTimer = types.Int64Value(value.Int())
	} else {
		data.StatsTimer = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/tcp-mss/adjust-mss"); !data.TcpAdjustMssEnable.IsNull() {
		if value.Exists() {
			data.TcpAdjustMssEnable = types.BoolValue(value.Bool())
		}
	} else {
		data.TcpAdjustMssEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/tcp-mss/tcp-adjust-mss"); value.Exists() && !data.TcpAdjustMssSize.IsNull() {
		data.TcpAdjustMssSize = types.Int64Value(value.Int())
	} else {
		data.TcpAdjustMssSize = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ble/scan-state"); !data.BleScan.IsNull() {
		if value.Exists() {
			data.BleScan = types.BoolValue(value.Bool())
		}
	} else {
		data.BleScan = types.BoolNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *WirelessAPJoinProfile) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-window/window-size"); value.Exists() {
		data.CapwapWindowSize = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ap-country/country-code"); value.Exists() {
		data.Country = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/device-mgmt/ssh"); value.Exists() {
		data.Ssh = types.BoolValue(value.Bool())
	} else {
		data.Ssh = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/username"); value.Exists() {
		data.MgmtuserUsername = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/password"); value.Exists() {
		data.MgmtuserPassword = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/password-type"); value.Exists() {
		data.MgmtuserPasswordType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/secret"); value.Exists() {
		data.MgmtuserSecret = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/secret-type"); value.Exists() {
		data.MgmtuserSecretType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ntp-server-info/ntp-address"); value.Exists() {
		data.NtpIp = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/host"); value.Exists() {
		data.SyslogHost = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/facility-value"); value.Exists() {
		data.SyslogFacility = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/log-level"); value.Exists() {
		data.SyslogLevel = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apphost/enable"); value.Exists() {
		data.Apphost = types.BoolValue(value.Bool())
	} else {
		data.Apphost = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/client-limit/max-cfg-clients"); value.Exists() {
		data.AssociationLimit = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/awips-enabled"); value.Exists() {
		data.Awips = types.BoolValue(value.Bool())
	} else {
		data.Awips = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/awips-forensic-enabled"); value.Exists() {
		data.AwipsForensic = types.BoolValue(value.Bool())
	} else {
		data.AwipsForensic = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/retransmit-timer/count"); value.Exists() {
		data.CapwapRetransmitCount = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/retransmit-timer/interval"); value.Exists() {
		data.CapwapRetransmitInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/discovery-timeout"); value.Exists() {
		data.CapwapTimersDiscoveryTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/fast-heart-beat-timeout"); value.Exists() {
		data.CapwapTimersFastHeartbeatTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/heart-beat-timeout"); value.Exists() {
		data.CapwapTimersHeartbeatTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/primary-discovery-timeout"); value.Exists() {
		data.CapwapTimersPrimaryDiscoveryTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/primed-join-timeout"); value.Exists() {
		data.CapwapTimersPrimedJoinTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/primary-controller-name"); value.Exists() {
		data.CapwapBackupPrimaryName = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/primary-controller-ip"); value.Exists() {
		data.CapwapBackupPrimaryIp = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/secondary-controller-name"); value.Exists() {
		data.CapwapBackupSecondaryName = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/secondary-controller-ip"); value.Exists() {
		data.CapwapBackupSecondaryIp = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/fallback-enabled"); value.Exists() {
		data.CapwapFallback = types.BoolValue(value.Bool())
	} else {
		data.CapwapFallback = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/private-ip-discovery"); value.Exists() {
		data.CapwapDiscoveryPrivate = types.BoolValue(value.Bool())
	} else {
		data.CapwapDiscoveryPrivate = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/public-ip-discovery"); value.Exists() {
		data.CapwapDiscoveryPublic = types.BoolValue(value.Bool())
	} else {
		data.CapwapDiscoveryPublic = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/cdp/cdp-enable"); value.Exists() {
		data.Cdp = types.BoolValue(value.Bool())
	} else {
		data.Cdp = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dot1x-eap-type-info/dot1x-eap-type"); value.Exists() {
		data.Dot1xEapType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login-credentials/dot1x-username"); value.Exists() {
		data.Dot1xUsername = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login-credentials/dot1x-password"); value.Exists() {
		data.Dot1xPassword = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login-credentials/dot1x-password-type"); value.Exists() {
		data.Dot1xPasswordType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hyperlocation/hyperlocation-enable"); value.Exists() {
		data.Hyperlocation = types.BoolValue(value.Bool())
	} else {
		data.Hyperlocation = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dhcp-fallback/dhcp-fallback"); value.Exists() {
		data.IpDhcpFallback = types.BoolValue(value.Bool())
	} else {
		data.IpDhcpFallback = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lag-info/ap-lag-enabled"); value.Exists() {
		data.Lag = types.BoolValue(value.Bool())
	} else {
		data.Lag = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/led-state/led-state"); value.Exists() {
		data.Led = types.BoolValue(value.Bool())
	} else {
		data.Led = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/mesh/mesh-profile-name"); value.Exists() {
		data.MeshProfile = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection"); value.Exists() {
		data.RogueDetectionEnable = types.BoolValue(value.Bool())
	} else {
		data.RogueDetectionEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection-min-rssi"); value.Exists() {
		data.RogueDetectionMinRssi = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection-transient-interval"); value.Exists() {
		data.RogueDetectionMinTransientTime = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/rogue-detection-monitor-mode-report-interval"); value.Exists() {
		data.RogueDetectionReportInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/enable"); value.Exists() {
		data.StatisticsApSystemMonitoringEnable = types.BoolValue(value.Bool())
	} else {
		data.StatisticsApSystemMonitoringEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/alarms-enable"); value.Exists() {
		data.StatisticsApSystemMonitoringAlarmEnable = types.BoolValue(true)
	} else {
		data.StatisticsApSystemMonitoringAlarmEnable = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/alarm-hold-time"); value.Exists() {
		data.StatisticsApSystemMonitoringAlarmHoldTime = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/trap-retx-time"); value.Exists() {
		data.StatisticsApSystemMonitoringAlarmRetransmitTime = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/cpu-threshold"); value.Exists() {
		data.StatisticsApSystemMonitoringCpuThreshold = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/mem-threshold"); value.Exists() {
		data.StatisticsApSystemMonitoringMemThreshold = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/sample-intvl"); value.Exists() {
		data.StatisticsApSystemMonitoringSamplingInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/stats-intvl"); value.Exists() {
		data.StatisticsApSystemMonitoringStatsInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/traffic-distribution/status"); value.Exists() {
		data.StatisticsTrafficDistribution = types.BoolValue(value.Bool())
	} else {
		data.StatisticsTrafficDistribution = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/traffic-distribution/interval"); value.Exists() {
		data.StatisticsTrafficDistributionInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/radio-stats-monitor/enable"); value.Exists() {
		data.StatisticsApRadioMonitoringEnable = types.BoolValue(value.Bool())
	} else {
		data.StatisticsApRadioMonitoringEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/radio-stats-monitor/sample-intvl"); value.Exists() {
		data.StatisticsApRadioMonitoringSamplingInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-timer/stats-timer"); value.Exists() {
		data.StatsTimer = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/tcp-mss/adjust-mss"); value.Exists() {
		data.TcpAdjustMssEnable = types.BoolValue(value.Bool())
	} else {
		data.TcpAdjustMssEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/tcp-mss/tcp-adjust-mss"); value.Exists() {
		data.TcpAdjustMssSize = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ble/scan-state"); value.Exists() {
		data.BleScan = types.BoolValue(value.Bool())
	} else {
		data.BleScan = types.BoolNull()
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *WirelessAPJoinProfileData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-window/window-size"); value.Exists() {
		data.CapwapWindowSize = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ap-country/country-code"); value.Exists() {
		data.Country = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/device-mgmt/ssh"); value.Exists() {
		data.Ssh = types.BoolValue(value.Bool())
	} else {
		data.Ssh = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/username"); value.Exists() {
		data.MgmtuserUsername = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/password"); value.Exists() {
		data.MgmtuserPassword = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/password-type"); value.Exists() {
		data.MgmtuserPasswordType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/secret"); value.Exists() {
		data.MgmtuserSecret = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/user-mgmt/secret-type"); value.Exists() {
		data.MgmtuserSecretType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ntp-server-info/ntp-address"); value.Exists() {
		data.NtpIp = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/host"); value.Exists() {
		data.SyslogHost = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/facility-value"); value.Exists() {
		data.SyslogFacility = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/syslog/log-level"); value.Exists() {
		data.SyslogLevel = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apphost/enable"); value.Exists() {
		data.Apphost = types.BoolValue(value.Bool())
	} else {
		data.Apphost = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/client-limit/max-cfg-clients"); value.Exists() {
		data.AssociationLimit = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/awips-enabled"); value.Exists() {
		data.Awips = types.BoolValue(value.Bool())
	} else {
		data.Awips = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/awips-forensic-enabled"); value.Exists() {
		data.AwipsForensic = types.BoolValue(value.Bool())
	} else {
		data.AwipsForensic = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/retransmit-timer/count"); value.Exists() {
		data.CapwapRetransmitCount = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/retransmit-timer/interval"); value.Exists() {
		data.CapwapRetransmitInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/discovery-timeout"); value.Exists() {
		data.CapwapTimersDiscoveryTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/fast-heart-beat-timeout"); value.Exists() {
		data.CapwapTimersFastHeartbeatTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/heart-beat-timeout"); value.Exists() {
		data.CapwapTimersHeartbeatTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/primary-discovery-timeout"); value.Exists() {
		data.CapwapTimersPrimaryDiscoveryTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/capwap-timer/primed-join-timeout"); value.Exists() {
		data.CapwapTimersPrimedJoinTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/primary-controller-name"); value.Exists() {
		data.CapwapBackupPrimaryName = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/primary-controller-ip"); value.Exists() {
		data.CapwapBackupPrimaryIp = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/secondary-controller-name"); value.Exists() {
		data.CapwapBackupSecondaryName = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/secondary-controller-ip"); value.Exists() {
		data.CapwapBackupSecondaryIp = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/backup-controllers/fallback-enabled"); value.Exists() {
		data.CapwapFallback = types.BoolValue(value.Bool())
	} else {
		data.CapwapFallback = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/private-ip-discovery"); value.Exists() {
		data.CapwapDiscoveryPrivate = types.BoolValue(value.Bool())
	} else {
		data.CapwapDiscoveryPrivate = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/public-ip-discovery"); value.Exists() {
		data.CapwapDiscoveryPublic = types.BoolValue(value.Bool())
	} else {
		data.CapwapDiscoveryPublic = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/cdp/cdp-enable"); value.Exists() {
		data.Cdp = types.BoolValue(value.Bool())
	} else {
		data.Cdp = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dot1x-eap-type-info/dot1x-eap-type"); value.Exists() {
		data.Dot1xEapType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login-credentials/dot1x-username"); value.Exists() {
		data.Dot1xUsername = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login-credentials/dot1x-password"); value.Exists() {
		data.Dot1xPassword = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login-credentials/dot1x-password-type"); value.Exists() {
		data.Dot1xPasswordType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/hyperlocation/hyperlocation-enable"); value.Exists() {
		data.Hyperlocation = types.BoolValue(value.Bool())
	} else {
		data.Hyperlocation = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dhcp-fallback/dhcp-fallback"); value.Exists() {
		data.IpDhcpFallback = types.BoolValue(value.Bool())
	} else {
		data.IpDhcpFallback = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lag-info/ap-lag-enabled"); value.Exists() {
		data.Lag = types.BoolValue(value.Bool())
	} else {
		data.Lag = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/led-state/led-state"); value.Exists() {
		data.Led = types.BoolValue(value.Bool())
	} else {
		data.Led = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/mesh/mesh-profile-name"); value.Exists() {
		data.MeshProfile = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection"); value.Exists() {
		data.RogueDetectionEnable = types.BoolValue(value.Bool())
	} else {
		data.RogueDetectionEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection-min-rssi"); value.Exists() {
		data.RogueDetectionMinRssi = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/ap-rogue-detection-transient-interval"); value.Exists() {
		data.RogueDetectionMinTransientTime = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rogue-detection/rogue-detection-monitor-mode-report-interval"); value.Exists() {
		data.RogueDetectionReportInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/enable"); value.Exists() {
		data.StatisticsApSystemMonitoringEnable = types.BoolValue(value.Bool())
	} else {
		data.StatisticsApSystemMonitoringEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/alarms-enable"); value.Exists() {
		data.StatisticsApSystemMonitoringAlarmEnable = types.BoolValue(true)
	} else {
		data.StatisticsApSystemMonitoringAlarmEnable = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/alarm-hold-time"); value.Exists() {
		data.StatisticsApSystemMonitoringAlarmHoldTime = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/trap-retx-time"); value.Exists() {
		data.StatisticsApSystemMonitoringAlarmRetransmitTime = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/cpu-threshold"); value.Exists() {
		data.StatisticsApSystemMonitoringCpuThreshold = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/mem-threshold"); value.Exists() {
		data.StatisticsApSystemMonitoringMemThreshold = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/sample-intvl"); value.Exists() {
		data.StatisticsApSystemMonitoringSamplingInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-monitor/stats-intvl"); value.Exists() {
		data.StatisticsApSystemMonitoringStatsInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/traffic-distribution/status"); value.Exists() {
		data.StatisticsTrafficDistribution = types.BoolValue(value.Bool())
	} else {
		data.StatisticsTrafficDistribution = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/traffic-distribution/interval"); value.Exists() {
		data.StatisticsTrafficDistributionInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/radio-stats-monitor/enable"); value.Exists() {
		data.StatisticsApRadioMonitoringEnable = types.BoolValue(value.Bool())
	} else {
		data.StatisticsApRadioMonitoringEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/radio-stats-monitor/sample-intvl"); value.Exists() {
		data.StatisticsApRadioMonitoringSamplingInterval = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/stats-timer/stats-timer"); value.Exists() {
		data.StatsTimer = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/tcp-mss/adjust-mss"); value.Exists() {
		data.TcpAdjustMssEnable = types.BoolValue(value.Bool())
	} else {
		data.TcpAdjustMssEnable = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/tcp-mss/tcp-adjust-mss"); value.Exists() {
		data.TcpAdjustMssSize = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ble/scan-state"); value.Exists() {
		data.BleScan = types.BoolValue(value.Bool())
	} else {
		data.BleScan = types.BoolNull()
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *WirelessAPJoinProfile) addDeletedItemsXML(ctx context.Context, state WirelessAPJoinProfile, body string) string {
	b := netconf.NewBody(body)
	if !state.BleScan.IsNull() && data.BleScan.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/ble/scan-state")
	}
	if !state.TcpAdjustMssSize.IsNull() && data.TcpAdjustMssSize.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/tcp-mss/tcp-adjust-mss")
	}
	if !state.TcpAdjustMssEnable.IsNull() && data.TcpAdjustMssEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/tcp-mss/adjust-mss")
	}
	if !state.StatsTimer.IsNull() && data.StatsTimer.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-timer/stats-timer")
	}
	if !state.StatisticsApRadioMonitoringSamplingInterval.IsNull() && data.StatisticsApRadioMonitoringSamplingInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/radio-stats-monitor/sample-intvl")
	}
	if !state.StatisticsApRadioMonitoringEnable.IsNull() && data.StatisticsApRadioMonitoringEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/radio-stats-monitor/enable")
	}
	if !state.StatisticsTrafficDistributionInterval.IsNull() && data.StatisticsTrafficDistributionInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/traffic-distribution/interval")
	}
	if !state.StatisticsTrafficDistribution.IsNull() && data.StatisticsTrafficDistribution.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/traffic-distribution/status")
	}
	if !state.StatisticsApSystemMonitoringStatsInterval.IsNull() && data.StatisticsApSystemMonitoringStatsInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-monitor/stats-intvl")
	}
	if !state.StatisticsApSystemMonitoringSamplingInterval.IsNull() && data.StatisticsApSystemMonitoringSamplingInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-monitor/sample-intvl")
	}
	if !state.StatisticsApSystemMonitoringMemThreshold.IsNull() && data.StatisticsApSystemMonitoringMemThreshold.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-monitor/mem-threshold")
	}
	if !state.StatisticsApSystemMonitoringCpuThreshold.IsNull() && data.StatisticsApSystemMonitoringCpuThreshold.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-monitor/cpu-threshold")
	}
	if !state.StatisticsApSystemMonitoringAlarmRetransmitTime.IsNull() && data.StatisticsApSystemMonitoringAlarmRetransmitTime.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-monitor/trap-retx-time")
	}
	if !state.StatisticsApSystemMonitoringAlarmHoldTime.IsNull() && data.StatisticsApSystemMonitoringAlarmHoldTime.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-monitor/alarm-hold-time")
	}
	if !state.StatisticsApSystemMonitoringAlarmEnable.IsNull() && data.StatisticsApSystemMonitoringAlarmEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-monitor/alarms-enable")
	}
	if !state.StatisticsApSystemMonitoringEnable.IsNull() && data.StatisticsApSystemMonitoringEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/stats-monitor/enable")
	}
	if !state.RogueDetectionReportInterval.IsNull() && data.RogueDetectionReportInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/rogue-detection/rogue-detection-monitor-mode-report-interval")
	}
	if !state.RogueDetectionMinTransientTime.IsNull() && data.RogueDetectionMinTransientTime.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/rogue-detection/ap-rogue-detection-transient-interval")
	}
	if !state.RogueDetectionMinRssi.IsNull() && data.RogueDetectionMinRssi.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/rogue-detection/ap-rogue-detection-min-rssi")
	}
	if !state.RogueDetectionEnable.IsNull() && data.RogueDetectionEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/rogue-detection/ap-rogue-detection")
	}
	if !state.MeshProfile.IsNull() && data.MeshProfile.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/mesh/mesh-profile-name")
	}
	if !state.Led.IsNull() && data.Led.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/led-state/led-state")
	}
	if !state.Lag.IsNull() && data.Lag.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/lag-info/ap-lag-enabled")
	}
	if !state.IpDhcpFallback.IsNull() && data.IpDhcpFallback.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/dhcp-fallback/dhcp-fallback")
	}
	if !state.Hyperlocation.IsNull() && data.Hyperlocation.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/hyperlocation/hyperlocation-enable")
	}
	if !state.Dot1xPasswordType.IsNull() && data.Dot1xPasswordType.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/login-credentials/dot1x-password-type")
	}
	if !state.Dot1xPassword.IsNull() && data.Dot1xPassword.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/login-credentials/dot1x-password")
	}
	if !state.Dot1xUsername.IsNull() && data.Dot1xUsername.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/login-credentials/dot1x-username")
	}
	if !state.Dot1xEapType.IsNull() && data.Dot1xEapType.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/dot1x-eap-type-info/dot1x-eap-type")
	}
	if !state.Cdp.IsNull() && data.Cdp.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/cdp/cdp-enable")
	}
	if !state.CapwapDiscoveryPublic.IsNull() && data.CapwapDiscoveryPublic.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/public-ip-discovery")
	}
	if !state.CapwapDiscoveryPrivate.IsNull() && data.CapwapDiscoveryPrivate.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/private-ip-discovery")
	}
	if !state.CapwapFallback.IsNull() && data.CapwapFallback.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/backup-controllers/fallback-enabled")
	}
	if !state.CapwapBackupSecondaryIp.IsNull() && data.CapwapBackupSecondaryIp.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/backup-controllers/secondary-controller-ip")
	}
	if !state.CapwapBackupSecondaryName.IsNull() && data.CapwapBackupSecondaryName.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/backup-controllers/secondary-controller-name")
	}
	if !state.CapwapBackupPrimaryIp.IsNull() && data.CapwapBackupPrimaryIp.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/backup-controllers/primary-controller-ip")
	}
	if !state.CapwapBackupPrimaryName.IsNull() && data.CapwapBackupPrimaryName.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/backup-controllers/primary-controller-name")
	}
	if !state.CapwapTimersPrimedJoinTimeout.IsNull() && data.CapwapTimersPrimedJoinTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/capwap-timer/primed-join-timeout")
	}
	if !state.CapwapTimersPrimaryDiscoveryTimeout.IsNull() && data.CapwapTimersPrimaryDiscoveryTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/capwap-timer/primary-discovery-timeout")
	}
	if !state.CapwapTimersHeartbeatTimeout.IsNull() && data.CapwapTimersHeartbeatTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/capwap-timer/heart-beat-timeout")
	}
	if !state.CapwapTimersFastHeartbeatTimeout.IsNull() && data.CapwapTimersFastHeartbeatTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/capwap-timer/fast-heart-beat-timeout")
	}
	if !state.CapwapTimersDiscoveryTimeout.IsNull() && data.CapwapTimersDiscoveryTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/capwap-timer/discovery-timeout")
	}
	if !state.CapwapRetransmitInterval.IsNull() && data.CapwapRetransmitInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/retransmit-timer/interval")
	}
	if !state.CapwapRetransmitCount.IsNull() && data.CapwapRetransmitCount.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/retransmit-timer/count")
	}
	if !state.AwipsForensic.IsNull() && data.AwipsForensic.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/awips-forensic-enabled")
	}
	if !state.Awips.IsNull() && data.Awips.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/awips-enabled")
	}
	if !state.AssociationLimit.IsNull() && data.AssociationLimit.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/client-limit/max-cfg-clients")
	}
	if !state.Apphost.IsNull() && data.Apphost.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/apphost/enable")
	}
	if !state.SyslogLevel.IsNull() && data.SyslogLevel.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/syslog/log-level")
	}
	if !state.SyslogFacility.IsNull() && data.SyslogFacility.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/syslog/facility-value")
	}
	if !state.SyslogHost.IsNull() && data.SyslogHost.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/syslog/host")
	}
	if !state.NtpIp.IsNull() && data.NtpIp.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/ntp-server-info/ntp-address")
	}
	if !state.MgmtuserSecretType.IsNull() && data.MgmtuserSecretType.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/user-mgmt/secret-type")
	}
	if !state.MgmtuserSecret.IsNull() && data.MgmtuserSecret.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/user-mgmt/secret")
	}
	if !state.MgmtuserPasswordType.IsNull() && data.MgmtuserPasswordType.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/user-mgmt/password-type")
	}
	if !state.MgmtuserPassword.IsNull() && data.MgmtuserPassword.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/user-mgmt/password")
	}
	if !state.MgmtuserUsername.IsNull() && data.MgmtuserUsername.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/user-mgmt/username")
	}
	if !state.Ssh.IsNull() && data.Ssh.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/device-mgmt/ssh")
	}
	if !state.Country.IsNull() && data.Country.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/ap-country/country-code")
	}
	if !state.CapwapWindowSize.IsNull() && data.CapwapWindowSize.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/capwap-window/window-size")
	}
	if !state.Description.IsNull() && data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *WirelessAPJoinProfile) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.BleScan.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/ble/scan-state")
	}
	if !data.TcpAdjustMssSize.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/tcp-mss/tcp-adjust-mss")
	}
	if !data.TcpAdjustMssEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/tcp-mss/adjust-mss")
	}
	if !data.StatsTimer.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-timer/stats-timer")
	}
	if !data.StatisticsApRadioMonitoringSamplingInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/radio-stats-monitor/sample-intvl")
	}
	if !data.StatisticsApRadioMonitoringEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/radio-stats-monitor/enable")
	}
	if !data.StatisticsTrafficDistributionInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/traffic-distribution/interval")
	}
	if !data.StatisticsTrafficDistribution.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/traffic-distribution/status")
	}
	if !data.StatisticsApSystemMonitoringStatsInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-monitor/stats-intvl")
	}
	if !data.StatisticsApSystemMonitoringSamplingInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-monitor/sample-intvl")
	}
	if !data.StatisticsApSystemMonitoringMemThreshold.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-monitor/mem-threshold")
	}
	if !data.StatisticsApSystemMonitoringCpuThreshold.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-monitor/cpu-threshold")
	}
	if !data.StatisticsApSystemMonitoringAlarmRetransmitTime.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-monitor/trap-retx-time")
	}
	if !data.StatisticsApSystemMonitoringAlarmHoldTime.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-monitor/alarm-hold-time")
	}
	if !data.StatisticsApSystemMonitoringAlarmEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-monitor/alarms-enable")
	}
	if !data.StatisticsApSystemMonitoringEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/stats-monitor/enable")
	}
	if !data.RogueDetectionReportInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/rogue-detection/rogue-detection-monitor-mode-report-interval")
	}
	if !data.RogueDetectionMinTransientTime.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/rogue-detection/ap-rogue-detection-transient-interval")
	}
	if !data.RogueDetectionMinRssi.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/rogue-detection/ap-rogue-detection-min-rssi")
	}
	if !data.RogueDetectionEnable.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/rogue-detection/ap-rogue-detection")
	}
	if !data.MeshProfile.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/mesh/mesh-profile-name")
	}
	if !data.Led.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/led-state/led-state")
	}
	if !data.Lag.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/lag-info/ap-lag-enabled")
	}
	if !data.IpDhcpFallback.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/dhcp-fallback/dhcp-fallback")
	}
	if !data.Hyperlocation.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/hyperlocation/hyperlocation-enable")
	}
	if !data.Dot1xPasswordType.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/login-credentials/dot1x-password-type")
	}
	if !data.Dot1xPassword.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/login-credentials/dot1x-password")
	}
	if !data.Dot1xUsername.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/login-credentials/dot1x-username")
	}
	if !data.Dot1xEapType.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/dot1x-eap-type-info/dot1x-eap-type")
	}
	if !data.Cdp.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/cdp/cdp-enable")
	}
	if !data.CapwapDiscoveryPublic.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/public-ip-discovery")
	}
	if !data.CapwapDiscoveryPrivate.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/private-ip-discovery")
	}
	if !data.CapwapFallback.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/backup-controllers/fallback-enabled")
	}
	if !data.CapwapBackupSecondaryIp.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/backup-controllers/secondary-controller-ip")
	}
	if !data.CapwapBackupSecondaryName.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/backup-controllers/secondary-controller-name")
	}
	if !data.CapwapBackupPrimaryIp.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/backup-controllers/primary-controller-ip")
	}
	if !data.CapwapBackupPrimaryName.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/backup-controllers/primary-controller-name")
	}
	if !data.CapwapTimersPrimedJoinTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/capwap-timer/primed-join-timeout")
	}
	if !data.CapwapTimersPrimaryDiscoveryTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/capwap-timer/primary-discovery-timeout")
	}
	if !data.CapwapTimersHeartbeatTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/capwap-timer/heart-beat-timeout")
	}
	if !data.CapwapTimersFastHeartbeatTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/capwap-timer/fast-heart-beat-timeout")
	}
	if !data.CapwapTimersDiscoveryTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/capwap-timer/discovery-timeout")
	}
	if !data.CapwapRetransmitInterval.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/retransmit-timer/interval")
	}
	if !data.CapwapRetransmitCount.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/retransmit-timer/count")
	}
	if !data.AwipsForensic.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/awips-forensic-enabled")
	}
	if !data.Awips.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/awips-enabled")
	}
	if !data.AssociationLimit.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/client-limit/max-cfg-clients")
	}
	if !data.Apphost.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/apphost/enable")
	}
	if !data.SyslogLevel.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/syslog/log-level")
	}
	if !data.SyslogFacility.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/syslog/facility-value")
	}
	if !data.SyslogHost.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/syslog/host")
	}
	if !data.NtpIp.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/ntp-server-info/ntp-address")
	}
	if !data.MgmtuserSecretType.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/user-mgmt/secret-type")
	}
	if !data.MgmtuserSecret.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/user-mgmt/secret")
	}
	if !data.MgmtuserPasswordType.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/user-mgmt/password-type")
	}
	if !data.MgmtuserPassword.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/user-mgmt/password")
	}
	if !data.MgmtuserUsername.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/user-mgmt/username")
	}
	if !data.Ssh.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/device-mgmt/ssh")
	}
	if !data.Country.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/ap-country/country-code")
	}
	if !data.CapwapWindowSize.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/capwap-window/window-size")
	}
	if !data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
