// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessSiteTag struct {
	Device        types.String `tfsdk:"device"`
	Id            types.String `tfsdk:"id"`
	SiteTagName   types.String `tfsdk:"site_tag_name"`
	Description   types.String `tfsdk:"description"`
	ApJoinProfile types.String `tfsdk:"ap_join_profile"`
	FlexProfile   types.String `tfsdk:"flex_profile"`
	LocalSite     types.Bool   `tfsdk:"local_site"`
}

type WirelessSiteTagData struct {
	Device        types.String `tfsdk:"device"`
	Id            types.String `tfsdk:"id"`
	SiteTagName   types.String `tfsdk:"site_tag_name"`
	Description   types.String `tfsdk:"description"`
	ApJoinProfile types.String `tfsdk:"ap_join_profile"`
	FlexProfile   types.String `tfsdk:"flex_profile"`
	LocalSite     types.Bool   `tfsdk:"local_site"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data WirelessSiteTag) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-site-cfg:site-cfg-data/site-tag-configs/site-tag-config=%s", url.QueryEscape(fmt.Sprintf("%v", data.SiteTagName.ValueString())))
}

func (data WirelessSiteTagData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-site-cfg:site-cfg-data/site-tag-configs/site-tag-config=%s", url.QueryEscape(fmt.Sprintf("%v", data.SiteTagName.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data WirelessSiteTag) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-site-cfg:site-cfg-data/site-tag-configs/site-tag-config[site-tag-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.SiteTagName.ValueString()))
	return path
}

func (data WirelessSiteTagData) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-site-cfg:site-cfg-data/site-tag-configs/site-tag-config[site-tag-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.SiteTagName.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data WirelessSiteTag) toBodyXML(ctx context.Context, config WirelessSiteTag) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data WirelessSiteTag) addToBodyXML(ctx context.Context, config WirelessSiteTag, body netconf.Body) netconf.Body {
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *WirelessSiteTag) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *WirelessSiteTag) fromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *WirelessSiteTagData) fromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *WirelessSiteTag) addDeletedItemsXML(ctx context.Context, state WirelessSiteTag, body string) string {
	b := netconf.NewBody(body)

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *WirelessSiteTag) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
