// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessManagementInterface struct {
	Device        types.String `tfsdk:"device"`
	Id            types.String `tfsdk:"id"`
	DeleteMode    types.String `tfsdk:"delete_mode"`
	InterfaceName types.String `tfsdk:"interface_name"`
}

type WirelessManagementInterfaceData struct {
	Device        types.String `tfsdk:"device"`
	Id            types.String `tfsdk:"id"`
	InterfaceName types.String `tfsdk:"interface_name"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data WirelessManagementInterface) getPath() string {
	return "Cisco-IOS-XE-wireless-general-cfg:general-cfg-data/sim-l3-interface-cache-data"
}

func (data WirelessManagementInterfaceData) getPath() string {
	return "Cisco-IOS-XE-wireless-general-cfg:general-cfg-data/sim-l3-interface-cache-data"
}

// getXPath returns the XPath for NETCONF operations
func (data WirelessManagementInterface) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-general-cfg:general-cfg-data/sim-l3-interface-cache-data"
	return path
}

func (data WirelessManagementInterfaceData) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-general-cfg:general-cfg-data/sim-l3-interface-cache-data"
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data WirelessManagementInterface) toBodyXML(ctx context.Context, config WirelessManagementInterface) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data WirelessManagementInterface) addToBodyXML(ctx context.Context, config WirelessManagementInterface, body netconf.Body) netconf.Body {
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *WirelessManagementInterface) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *WirelessManagementInterface) fromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *WirelessManagementInterfaceData) fromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *WirelessManagementInterface) addDeletedItemsXML(ctx context.Context, state WirelessManagementInterface, body string) string {
	b := netconf.NewBody(body)

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *WirelessManagementInterface) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
