// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessMeshProfile struct {
	Device            types.String `tfsdk:"device"`
	Id                types.String `tfsdk:"id"`
	ProfileName       types.String `tfsdk:"profile_name"`
	Description       types.String `tfsdk:"description"`
	ConvergenceMethod types.String `tfsdk:"convergence_method"`
	MulticastMode     types.String `tfsdk:"multicast_mode"`
	Range             types.Int64  `tfsdk:"range"`
	SecurityMode      types.String `tfsdk:"security_mode"`
}

type WirelessMeshProfileData struct {
	Device            types.String `tfsdk:"device"`
	Id                types.String `tfsdk:"id"`
	ProfileName       types.String `tfsdk:"profile_name"`
	Description       types.String `tfsdk:"description"`
	ConvergenceMethod types.String `tfsdk:"convergence_method"`
	MulticastMode     types.String `tfsdk:"multicast_mode"`
	Range             types.Int64  `tfsdk:"range"`
	SecurityMode      types.String `tfsdk:"security_mode"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data WirelessMeshProfile) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-mesh-cfg:mesh-cfg-data/mesh-profiles/mesh-profile=%s", url.QueryEscape(fmt.Sprintf("%v", data.ProfileName.ValueString())))
}

func (data WirelessMeshProfileData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-mesh-cfg:mesh-cfg-data/mesh-profiles/mesh-profile=%s", url.QueryEscape(fmt.Sprintf("%v", data.ProfileName.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data WirelessMeshProfile) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-mesh-cfg:mesh-cfg-data/mesh-profiles/mesh-profile[profile-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.ProfileName.ValueString()))
	return path
}

func (data WirelessMeshProfileData) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-mesh-cfg:mesh-cfg-data/mesh-profiles/mesh-profile[profile-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.ProfileName.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data WirelessMeshProfile) toBodyXML(ctx context.Context, config WirelessMeshProfile) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data WirelessMeshProfile) addToBodyXML(ctx context.Context, config WirelessMeshProfile, body netconf.Body) netconf.Body {
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *WirelessMeshProfile) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *WirelessMeshProfile) fromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *WirelessMeshProfileData) fromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *WirelessMeshProfile) addDeletedItemsXML(ctx context.Context, state WirelessMeshProfile, body string) string {
	b := netconf.NewBody(body)

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *WirelessMeshProfile) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
