// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessWLANProfile struct {
	Device                            types.String `tfsdk:"device"`
	Id                                types.String `tfsdk:"id"`
	ProfileName                       types.String `tfsdk:"profile_name"`
	WlanId                            types.Int64  `tfsdk:"wlan_id"`
	Ssid                              types.String `tfsdk:"ssid"`
	WlanStatus                        types.Bool   `tfsdk:"wlan_status"`
	BroadcastSsid                     types.Bool   `tfsdk:"broadcast_ssid"`
	CcxAironetIesupport               types.Bool   `tfsdk:"ccx_aironet_iesupport"`
	PeerBlocking                      types.String `tfsdk:"peer_blocking"`
	SecurityWpaAkmDot1x               types.Bool   `tfsdk:"security_wpa_akm_dot1x"`
	SecurityWpaAkmFtDot1x             types.Bool   `tfsdk:"security_wpa_akm_ft_dot1x"`
	SecurityWpaAkmPsk                 types.Bool   `tfsdk:"security_wpa_akm_psk"`
	SecurityWpaAkmFtPsk               types.Bool   `tfsdk:"security_wpa_akm_ft_psk"`
	SecurityWpaAkmSae                 types.Bool   `tfsdk:"security_wpa_akm_sae"`
	SecurityWpaAkmFtSae               types.Bool   `tfsdk:"security_wpa_akm_ft_sae"`
	SecurityWpaWpa2CiphersAes         types.Bool   `tfsdk:"security_wpa_wpa2_ciphers_aes"`
	SecurityWpaWpa2CiphersGcmp128     types.Bool   `tfsdk:"security_wpa_wpa2_ciphers_gcmp128"`
	SecurityWpaWpa2CiphersGcmp256     types.Bool   `tfsdk:"security_wpa_wpa2_ciphers_gcmp256"`
	SecurityWpaWpa3                   types.Bool   `tfsdk:"security_wpa_wpa3"`
	SecurityWpaPskKeyFormat           types.String `tfsdk:"security_wpa_psk_key_format"`
	SecurityWpaPskKeyEncryption       types.String `tfsdk:"security_wpa_psk_key_encryption"`
	SecurityWpaPskKey                 types.String `tfsdk:"security_wpa_psk_key"`
	SecurityWpaPskKeyWO               types.String `tfsdk:"security_wpa_psk_key_wo"`
	SecurityWpaPskKeyWOVersion        types.Int64  `tfsdk:"security_wpa_psk_key_wo_version"`
	SecurityDot1xAuthenticationList   types.String `tfsdk:"security_dot1x_authentication_list"`
	SecurityWebAuth                   types.Bool   `tfsdk:"security_web_auth"`
	SecurityWebAuthAuthenticationList types.String `tfsdk:"security_web_auth_authentication_list"`
	SecurityWebAuthParameterMap       types.String `tfsdk:"security_web_auth_parameter_map"`
	SecurityFt                        types.String `tfsdk:"security_ft"`
	SecurityFtOverTheDs               types.Bool   `tfsdk:"security_ft_over_the_ds"`
	MacFiltering                      types.String `tfsdk:"mac_filtering"`
	LoadBalance                       types.Bool   `tfsdk:"load_balance"`
	Wmm                               types.String `tfsdk:"wmm"`
}

type WirelessWLANProfileData struct {
	Device                            types.String `tfsdk:"device"`
	Id                                types.String `tfsdk:"id"`
	ProfileName                       types.String `tfsdk:"profile_name"`
	WlanId                            types.Int64  `tfsdk:"wlan_id"`
	Ssid                              types.String `tfsdk:"ssid"`
	WlanStatus                        types.Bool   `tfsdk:"wlan_status"`
	BroadcastSsid                     types.Bool   `tfsdk:"broadcast_ssid"`
	CcxAironetIesupport               types.Bool   `tfsdk:"ccx_aironet_iesupport"`
	PeerBlocking                      types.String `tfsdk:"peer_blocking"`
	SecurityWpaAkmDot1x               types.Bool   `tfsdk:"security_wpa_akm_dot1x"`
	SecurityWpaAkmFtDot1x             types.Bool   `tfsdk:"security_wpa_akm_ft_dot1x"`
	SecurityWpaAkmPsk                 types.Bool   `tfsdk:"security_wpa_akm_psk"`
	SecurityWpaAkmFtPsk               types.Bool   `tfsdk:"security_wpa_akm_ft_psk"`
	SecurityWpaAkmSae                 types.Bool   `tfsdk:"security_wpa_akm_sae"`
	SecurityWpaAkmFtSae               types.Bool   `tfsdk:"security_wpa_akm_ft_sae"`
	SecurityWpaWpa2CiphersAes         types.Bool   `tfsdk:"security_wpa_wpa2_ciphers_aes"`
	SecurityWpaWpa2CiphersGcmp128     types.Bool   `tfsdk:"security_wpa_wpa2_ciphers_gcmp128"`
	SecurityWpaWpa2CiphersGcmp256     types.Bool   `tfsdk:"security_wpa_wpa2_ciphers_gcmp256"`
	SecurityWpaWpa3                   types.Bool   `tfsdk:"security_wpa_wpa3"`
	SecurityWpaPskKeyFormat           types.String `tfsdk:"security_wpa_psk_key_format"`
	SecurityWpaPskKeyEncryption       types.String `tfsdk:"security_wpa_psk_key_encryption"`
	SecurityWpaPskKey                 types.String `tfsdk:"security_wpa_psk_key"`
	SecurityDot1xAuthenticationList   types.String `tfsdk:"security_dot1x_authentication_list"`
	SecurityWebAuth                   types.Bool   `tfsdk:"security_web_auth"`
	SecurityWebAuthAuthenticationList types.String `tfsdk:"security_web_auth_authentication_list"`
	SecurityWebAuthParameterMap       types.String `tfsdk:"security_web_auth_parameter_map"`
	SecurityFt                        types.String `tfsdk:"security_ft"`
	SecurityFtOverTheDs               types.Bool   `tfsdk:"security_ft_over_the_ds"`
	MacFiltering                      types.String `tfsdk:"mac_filtering"`
	LoadBalance                       types.Bool   `tfsdk:"load_balance"`
	Wmm                               types.String `tfsdk:"wmm"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data WirelessWLANProfile) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/wlan-cfg-entries/wlan-cfg-entry=%s", url.QueryEscape(fmt.Sprintf("%v", data.ProfileName.ValueString())))
}

func (data WirelessWLANProfileData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/wlan-cfg-entries/wlan-cfg-entry=%s", url.QueryEscape(fmt.Sprintf("%v", data.ProfileName.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data WirelessWLANProfile) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/wlan-cfg-entries/wlan-cfg-entry[profile-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.ProfileName.ValueString()))
	return path
}

func (data WirelessWLANProfileData) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/wlan-cfg-entries/wlan-cfg-entry[profile-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.ProfileName.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data WirelessWLANProfile) toBodyXML(ctx context.Context, config WirelessWLANProfile) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data WirelessWLANProfile) addToBodyXML(ctx context.Context, config WirelessWLANProfile, body netconf.Body) netconf.Body {
	if !data.ProfileName.IsNull() && !data.ProfileName.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/profile-name", data.ProfileName.ValueString())
	}
	if !data.WlanId.IsNull() && !data.WlanId.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wlan-id", strconv.FormatInt(data.WlanId.ValueInt64(), 10))
	}
	if !data.Ssid.IsNull() && !data.Ssid.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/apf-vap-id-data/ssid", data.Ssid.ValueString())
	}
	if !data.WlanStatus.IsNull() && !data.WlanStatus.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/apf-vap-id-data/wlan-status", data.WlanStatus.ValueBool())
	}
	if !data.BroadcastSsid.IsNull() && !data.BroadcastSsid.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/apf-vap-id-data/broadcast-ssid", data.BroadcastSsid.ValueBool())
	}
	if !data.CcxAironetIesupport.IsNull() && !data.CcxAironetIesupport.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/apf-vap-id-data/ccx-aironet-ie", data.CcxAironetIesupport.ValueBool())
	}
	if !data.PeerBlocking.IsNull() && !data.PeerBlocking.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/apf-vap-id-data/p2p-block-action", data.PeerBlocking.ValueString())
	}
	if !data.SecurityWpaAkmDot1x.IsNull() && !data.SecurityWpaAkmDot1x.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/auth-key-mgmt-dot1x", data.SecurityWpaAkmDot1x.ValueBool())
	}
	if !data.SecurityWpaAkmFtDot1x.IsNull() && !data.SecurityWpaAkmFtDot1x.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/auth-key-mgmt-ft-dot1x", data.SecurityWpaAkmFtDot1x.ValueBool())
	}
	if !data.SecurityWpaAkmPsk.IsNull() && !data.SecurityWpaAkmPsk.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/auth-key-mgmt-psk", data.SecurityWpaAkmPsk.ValueBool())
	}
	if !data.SecurityWpaAkmFtPsk.IsNull() && !data.SecurityWpaAkmFtPsk.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/auth-key-mgmt-ft-psk", data.SecurityWpaAkmFtPsk.ValueBool())
	}
	if !data.SecurityWpaAkmSae.IsNull() && !data.SecurityWpaAkmSae.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/auth-key-mgmt-sae", data.SecurityWpaAkmSae.ValueBool())
	}
	if !data.SecurityWpaAkmFtSae.IsNull() && !data.SecurityWpaAkmFtSae.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/auth-key-mgmt-ft-sae", data.SecurityWpaAkmFtSae.ValueBool())
	}
	if !data.SecurityWpaWpa2CiphersAes.IsNull() && !data.SecurityWpaWpa2CiphersAes.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wpa2-aes", data.SecurityWpaWpa2CiphersAes.ValueBool())
	}
	if !data.SecurityWpaWpa2CiphersGcmp128.IsNull() && !data.SecurityWpaWpa2CiphersGcmp128.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/rsn-cipher-suite-gcmp128", data.SecurityWpaWpa2CiphersGcmp128.ValueBool())
	}
	if !data.SecurityWpaWpa2CiphersGcmp256.IsNull() && !data.SecurityWpaWpa2CiphersGcmp256.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/rsn-cipher-suite-gcmp256", data.SecurityWpaWpa2CiphersGcmp256.ValueBool())
	}
	if !data.SecurityWpaWpa3.IsNull() && !data.SecurityWpaWpa3.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wpa3-enabled", data.SecurityWpaWpa3.ValueBool())
	}
	if !data.SecurityWpaPskKeyFormat.IsNull() && !data.SecurityWpaPskKeyFormat.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/psk-key-type", data.SecurityWpaPskKeyFormat.ValueString())
	}
	if !data.SecurityWpaPskKeyEncryption.IsNull() && !data.SecurityWpaPskKeyEncryption.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/psk-type", data.SecurityWpaPskKeyEncryption.ValueString())
	}
	if !data.SecurityWpaPskKey.IsNull() && !data.SecurityWpaPskKey.IsUnknown() {
		if !config.SecurityWpaPskKeyWO.IsNull() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/psk", config.SecurityWpaPskKeyWO.ValueString())
		} else {
			body = helpers.SetFromXPath(body, data.getXPath()+"/psk", data.SecurityWpaPskKey.ValueString())
		}
	}
	if !data.SecurityDot1xAuthenticationList.IsNull() && !data.SecurityDot1xAuthenticationList.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/authentication-list", data.SecurityDot1xAuthenticationList.ValueString())
	}
	if !data.SecurityWebAuth.IsNull() && !data.SecurityWebAuth.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/webauth-enabled", data.SecurityWebAuth.ValueBool())
	}
	if !data.SecurityWebAuthAuthenticationList.IsNull() && !data.SecurityWebAuthAuthenticationList.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/web-authc-list", data.SecurityWebAuthAuthenticationList.ValueString())
	}
	if !data.SecurityWebAuthParameterMap.IsNull() && !data.SecurityWebAuthParameterMap.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/web-auth-parameter-map", data.SecurityWebAuthParameterMap.ValueString())
	}
	if !data.SecurityFt.IsNull() && !data.SecurityFt.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/ft-mode", data.SecurityFt.ValueString())
	}
	if !data.SecurityFtOverTheDs.IsNull() && !data.SecurityFtOverTheDs.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/ft-over-ds", data.SecurityFtOverTheDs.ValueBool())
	}
	if !data.MacFiltering.IsNull() && !data.MacFiltering.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/mac-filtering-list", data.MacFiltering.ValueString())
	}
	if !data.LoadBalance.IsNull() && !data.LoadBalance.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/load-balance", data.LoadBalance.ValueBool())
	}
	if !data.Wmm.IsNull() && !data.Wmm.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/qos-wmm-status", data.Wmm.ValueString())
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *WirelessWLANProfile) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/profile-name"); value.Exists() && !data.ProfileName.IsNull() {
		data.ProfileName = types.StringValue(value.String())
	} else {
		data.ProfileName = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-id"); value.Exists() && !data.WlanId.IsNull() {
		data.WlanId = types.Int64Value(value.Int())
	} else {
		data.WlanId = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/ssid"); value.Exists() && !data.Ssid.IsNull() {
		data.Ssid = types.StringValue(value.String())
	} else {
		data.Ssid = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/wlan-status"); !data.WlanStatus.IsNull() {
		if value.Exists() {
			data.WlanStatus = types.BoolValue(value.Bool())
		}
	} else {
		data.WlanStatus = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/broadcast-ssid"); !data.BroadcastSsid.IsNull() {
		if value.Exists() {
			data.BroadcastSsid = types.BoolValue(value.Bool())
		}
	} else {
		data.BroadcastSsid = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/ccx-aironet-ie"); !data.CcxAironetIesupport.IsNull() {
		if value.Exists() {
			data.CcxAironetIesupport = types.BoolValue(value.Bool())
		}
	} else {
		data.CcxAironetIesupport = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/p2p-block-action"); value.Exists() && !data.PeerBlocking.IsNull() {
		data.PeerBlocking = types.StringValue(value.String())
	} else {
		data.PeerBlocking = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-dot1x"); !data.SecurityWpaAkmDot1x.IsNull() {
		if value.Exists() {
			data.SecurityWpaAkmDot1x = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaAkmDot1x = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-dot1x"); !data.SecurityWpaAkmFtDot1x.IsNull() {
		if value.Exists() {
			data.SecurityWpaAkmFtDot1x = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaAkmFtDot1x = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-psk"); !data.SecurityWpaAkmPsk.IsNull() {
		if value.Exists() {
			data.SecurityWpaAkmPsk = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaAkmPsk = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-psk"); !data.SecurityWpaAkmFtPsk.IsNull() {
		if value.Exists() {
			data.SecurityWpaAkmFtPsk = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaAkmFtPsk = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-sae"); !data.SecurityWpaAkmSae.IsNull() {
		if value.Exists() {
			data.SecurityWpaAkmSae = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaAkmSae = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-sae"); !data.SecurityWpaAkmFtSae.IsNull() {
		if value.Exists() {
			data.SecurityWpaAkmFtSae = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaAkmFtSae = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wpa2-aes"); !data.SecurityWpaWpa2CiphersAes.IsNull() {
		if value.Exists() {
			data.SecurityWpaWpa2CiphersAes = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaWpa2CiphersAes = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rsn-cipher-suite-gcmp128"); !data.SecurityWpaWpa2CiphersGcmp128.IsNull() {
		if value.Exists() {
			data.SecurityWpaWpa2CiphersGcmp128 = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaWpa2CiphersGcmp128 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rsn-cipher-suite-gcmp256"); !data.SecurityWpaWpa2CiphersGcmp256.IsNull() {
		if value.Exists() {
			data.SecurityWpaWpa2CiphersGcmp256 = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaWpa2CiphersGcmp256 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wpa3-enabled"); !data.SecurityWpaWpa3.IsNull() {
		if value.Exists() {
			data.SecurityWpaWpa3 = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWpaWpa3 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/psk-key-type"); value.Exists() && !data.SecurityWpaPskKeyFormat.IsNull() {
		data.SecurityWpaPskKeyFormat = types.StringValue(value.String())
	} else {
		data.SecurityWpaPskKeyFormat = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/psk-type"); value.Exists() && !data.SecurityWpaPskKeyEncryption.IsNull() {
		data.SecurityWpaPskKeyEncryption = types.StringValue(value.String())
	} else {
		data.SecurityWpaPskKeyEncryption = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/authentication-list"); value.Exists() && !data.SecurityDot1xAuthenticationList.IsNull() {
		data.SecurityDot1xAuthenticationList = types.StringValue(value.String())
	} else {
		data.SecurityDot1xAuthenticationList = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/webauth-enabled"); !data.SecurityWebAuth.IsNull() {
		if value.Exists() {
			data.SecurityWebAuth = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityWebAuth = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/web-authc-list"); value.Exists() && !data.SecurityWebAuthAuthenticationList.IsNull() {
		data.SecurityWebAuthAuthenticationList = types.StringValue(value.String())
	} else {
		data.SecurityWebAuthAuthenticationList = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/web-auth-parameter-map"); value.Exists() && !data.SecurityWebAuthParameterMap.IsNull() {
		data.SecurityWebAuthParameterMap = types.StringValue(value.String())
	} else {
		data.SecurityWebAuthParameterMap = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ft-mode"); value.Exists() && !data.SecurityFt.IsNull() {
		data.SecurityFt = types.StringValue(value.String())
	} else {
		data.SecurityFt = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ft-over-ds"); !data.SecurityFtOverTheDs.IsNull() {
		if value.Exists() {
			data.SecurityFtOverTheDs = types.BoolValue(value.Bool())
		}
	} else {
		data.SecurityFtOverTheDs = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/mac-filtering-list"); value.Exists() && !data.MacFiltering.IsNull() {
		data.MacFiltering = types.StringValue(value.String())
	} else {
		data.MacFiltering = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/load-balance"); !data.LoadBalance.IsNull() {
		if value.Exists() {
			data.LoadBalance = types.BoolValue(value.Bool())
		}
	} else {
		data.LoadBalance = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/qos-wmm-status"); value.Exists() && !data.Wmm.IsNull() {
		data.Wmm = types.StringValue(value.String())
	} else {
		data.Wmm = types.StringNull()
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *WirelessWLANProfile) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-id"); value.Exists() {
		data.WlanId = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/ssid"); value.Exists() {
		data.Ssid = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/wlan-status"); value.Exists() {
		data.WlanStatus = types.BoolValue(value.Bool())
	} else {
		data.WlanStatus = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/broadcast-ssid"); value.Exists() {
		data.BroadcastSsid = types.BoolValue(value.Bool())
	} else {
		data.BroadcastSsid = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/ccx-aironet-ie"); value.Exists() {
		data.CcxAironetIesupport = types.BoolValue(value.Bool())
	} else {
		data.CcxAironetIesupport = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/p2p-block-action"); value.Exists() {
		data.PeerBlocking = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-dot1x"); value.Exists() {
		data.SecurityWpaAkmDot1x = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmDot1x = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-dot1x"); value.Exists() {
		data.SecurityWpaAkmFtDot1x = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmFtDot1x = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-psk"); value.Exists() {
		data.SecurityWpaAkmPsk = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmPsk = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-psk"); value.Exists() {
		data.SecurityWpaAkmFtPsk = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmFtPsk = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-sae"); value.Exists() {
		data.SecurityWpaAkmSae = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmSae = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-sae"); value.Exists() {
		data.SecurityWpaAkmFtSae = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmFtSae = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wpa2-aes"); value.Exists() {
		data.SecurityWpaWpa2CiphersAes = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaWpa2CiphersAes = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rsn-cipher-suite-gcmp128"); value.Exists() {
		data.SecurityWpaWpa2CiphersGcmp128 = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaWpa2CiphersGcmp128 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rsn-cipher-suite-gcmp256"); value.Exists() {
		data.SecurityWpaWpa2CiphersGcmp256 = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaWpa2CiphersGcmp256 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wpa3-enabled"); value.Exists() {
		data.SecurityWpaWpa3 = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaWpa3 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/psk-key-type"); value.Exists() {
		data.SecurityWpaPskKeyFormat = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/psk-type"); value.Exists() {
		data.SecurityWpaPskKeyEncryption = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/psk"); value.Exists() {
		data.SecurityWpaPskKey = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/authentication-list"); value.Exists() {
		data.SecurityDot1xAuthenticationList = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/webauth-enabled"); value.Exists() {
		data.SecurityWebAuth = types.BoolValue(value.Bool())
	} else {
		data.SecurityWebAuth = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/web-authc-list"); value.Exists() {
		data.SecurityWebAuthAuthenticationList = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/web-auth-parameter-map"); value.Exists() {
		data.SecurityWebAuthParameterMap = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ft-mode"); value.Exists() {
		data.SecurityFt = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ft-over-ds"); value.Exists() {
		data.SecurityFtOverTheDs = types.BoolValue(value.Bool())
	} else {
		data.SecurityFtOverTheDs = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/mac-filtering-list"); value.Exists() {
		data.MacFiltering = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/load-balance"); value.Exists() {
		data.LoadBalance = types.BoolValue(value.Bool())
	} else {
		data.LoadBalance = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/qos-wmm-status"); value.Exists() {
		data.Wmm = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *WirelessWLANProfileData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-id"); value.Exists() {
		data.WlanId = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/ssid"); value.Exists() {
		data.Ssid = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/wlan-status"); value.Exists() {
		data.WlanStatus = types.BoolValue(value.Bool())
	} else {
		data.WlanStatus = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/broadcast-ssid"); value.Exists() {
		data.BroadcastSsid = types.BoolValue(value.Bool())
	} else {
		data.BroadcastSsid = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/ccx-aironet-ie"); value.Exists() {
		data.CcxAironetIesupport = types.BoolValue(value.Bool())
	} else {
		data.CcxAironetIesupport = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/apf-vap-id-data/p2p-block-action"); value.Exists() {
		data.PeerBlocking = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-dot1x"); value.Exists() {
		data.SecurityWpaAkmDot1x = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmDot1x = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-dot1x"); value.Exists() {
		data.SecurityWpaAkmFtDot1x = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmFtDot1x = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-psk"); value.Exists() {
		data.SecurityWpaAkmPsk = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmPsk = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-psk"); value.Exists() {
		data.SecurityWpaAkmFtPsk = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmFtPsk = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-sae"); value.Exists() {
		data.SecurityWpaAkmSae = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmSae = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/auth-key-mgmt-ft-sae"); value.Exists() {
		data.SecurityWpaAkmFtSae = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaAkmFtSae = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wpa2-aes"); value.Exists() {
		data.SecurityWpaWpa2CiphersAes = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaWpa2CiphersAes = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rsn-cipher-suite-gcmp128"); value.Exists() {
		data.SecurityWpaWpa2CiphersGcmp128 = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaWpa2CiphersGcmp128 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/rsn-cipher-suite-gcmp256"); value.Exists() {
		data.SecurityWpaWpa2CiphersGcmp256 = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaWpa2CiphersGcmp256 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wpa3-enabled"); value.Exists() {
		data.SecurityWpaWpa3 = types.BoolValue(value.Bool())
	} else {
		data.SecurityWpaWpa3 = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/psk-key-type"); value.Exists() {
		data.SecurityWpaPskKeyFormat = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/psk-type"); value.Exists() {
		data.SecurityWpaPskKeyEncryption = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/psk"); value.Exists() {
		data.SecurityWpaPskKey = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/authentication-list"); value.Exists() {
		data.SecurityDot1xAuthenticationList = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/webauth-enabled"); value.Exists() {
		data.SecurityWebAuth = types.BoolValue(value.Bool())
	} else {
		data.SecurityWebAuth = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/web-authc-list"); value.Exists() {
		data.SecurityWebAuthAuthenticationList = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/web-auth-parameter-map"); value.Exists() {
		data.SecurityWebAuthParameterMap = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ft-mode"); value.Exists() {
		data.SecurityFt = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/ft-over-ds"); value.Exists() {
		data.SecurityFtOverTheDs = types.BoolValue(value.Bool())
	} else {
		data.SecurityFtOverTheDs = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/mac-filtering-list"); value.Exists() {
		data.MacFiltering = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/load-balance"); value.Exists() {
		data.LoadBalance = types.BoolValue(value.Bool())
	} else {
		data.LoadBalance = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/qos-wmm-status"); value.Exists() {
		data.Wmm = types.StringValue(value.String())
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *WirelessWLANProfile) addDeletedItemsXML(ctx context.Context, state WirelessWLANProfile, body string) string {
	b := netconf.NewBody(body)
	if !state.Wmm.IsNull() && data.Wmm.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/qos-wmm-status")
	}
	if !state.LoadBalance.IsNull() && data.LoadBalance.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/load-balance")
	}
	if !state.MacFiltering.IsNull() && data.MacFiltering.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/mac-filtering-list")
	}
	if !state.SecurityFtOverTheDs.IsNull() && data.SecurityFtOverTheDs.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/ft-over-ds")
	}
	if !state.SecurityFt.IsNull() && data.SecurityFt.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/ft-mode")
	}
	if !state.SecurityWebAuthParameterMap.IsNull() && data.SecurityWebAuthParameterMap.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/web-auth-parameter-map")
	}
	if !state.SecurityWebAuthAuthenticationList.IsNull() && data.SecurityWebAuthAuthenticationList.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/web-authc-list")
	}
	if !state.SecurityWebAuth.IsNull() && data.SecurityWebAuth.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/webauth-enabled")
	}
	if !state.SecurityDot1xAuthenticationList.IsNull() && data.SecurityDot1xAuthenticationList.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/authentication-list")
	}
	if !state.SecurityWpaPskKey.IsNull() && data.SecurityWpaPskKey.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/psk")
	}
	if !state.SecurityWpaPskKeyEncryption.IsNull() && data.SecurityWpaPskKeyEncryption.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/psk-type")
	}
	if !state.SecurityWpaPskKeyFormat.IsNull() && data.SecurityWpaPskKeyFormat.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/psk-key-type")
	}
	if !state.SecurityWpaWpa3.IsNull() && data.SecurityWpaWpa3.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wpa3-enabled")
	}
	if !state.SecurityWpaWpa2CiphersGcmp256.IsNull() && data.SecurityWpaWpa2CiphersGcmp256.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/rsn-cipher-suite-gcmp256")
	}
	if !state.SecurityWpaWpa2CiphersGcmp128.IsNull() && data.SecurityWpaWpa2CiphersGcmp128.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/rsn-cipher-suite-gcmp128")
	}
	if !state.SecurityWpaWpa2CiphersAes.IsNull() && data.SecurityWpaWpa2CiphersAes.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wpa2-aes")
	}
	if !state.SecurityWpaAkmFtSae.IsNull() && data.SecurityWpaAkmFtSae.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/auth-key-mgmt-ft-sae")
	}
	if !state.SecurityWpaAkmSae.IsNull() && data.SecurityWpaAkmSae.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/auth-key-mgmt-sae")
	}
	if !state.SecurityWpaAkmFtPsk.IsNull() && data.SecurityWpaAkmFtPsk.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/auth-key-mgmt-ft-psk")
	}
	if !state.SecurityWpaAkmPsk.IsNull() && data.SecurityWpaAkmPsk.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/auth-key-mgmt-psk")
	}
	if !state.SecurityWpaAkmFtDot1x.IsNull() && data.SecurityWpaAkmFtDot1x.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/auth-key-mgmt-ft-dot1x")
	}
	if !state.SecurityWpaAkmDot1x.IsNull() && data.SecurityWpaAkmDot1x.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/auth-key-mgmt-dot1x")
	}
	if !state.PeerBlocking.IsNull() && data.PeerBlocking.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/apf-vap-id-data/p2p-block-action")
	}
	if !state.CcxAironetIesupport.IsNull() && data.CcxAironetIesupport.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/apf-vap-id-data/ccx-aironet-ie")
	}
	if !state.BroadcastSsid.IsNull() && data.BroadcastSsid.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/apf-vap-id-data/broadcast-ssid")
	}
	if !state.WlanStatus.IsNull() && data.WlanStatus.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/apf-vap-id-data/wlan-status")
	}
	if !state.Ssid.IsNull() && data.Ssid.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/apf-vap-id-data/ssid")
	}
	if !state.WlanId.IsNull() && data.WlanId.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wlan-id")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *WirelessWLANProfile) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.Wmm.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/qos-wmm-status")
	}
	if !data.LoadBalance.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/load-balance")
	}
	if !data.MacFiltering.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/mac-filtering-list")
	}
	if !data.SecurityFtOverTheDs.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/ft-over-ds")
	}
	if !data.SecurityFt.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/ft-mode")
	}
	if !data.SecurityWebAuthParameterMap.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/web-auth-parameter-map")
	}
	if !data.SecurityWebAuthAuthenticationList.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/web-authc-list")
	}
	if !data.SecurityWebAuth.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/webauth-enabled")
	}
	if !data.SecurityDot1xAuthenticationList.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/authentication-list")
	}
	if !data.SecurityWpaPskKey.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/psk")
	}
	if !data.SecurityWpaPskKeyEncryption.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/psk-type")
	}
	if !data.SecurityWpaPskKeyFormat.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/psk-key-type")
	}
	if !data.SecurityWpaWpa3.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wpa3-enabled")
	}
	if !data.SecurityWpaWpa2CiphersGcmp256.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/rsn-cipher-suite-gcmp256")
	}
	if !data.SecurityWpaWpa2CiphersGcmp128.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/rsn-cipher-suite-gcmp128")
	}
	if !data.SecurityWpaWpa2CiphersAes.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wpa2-aes")
	}
	if !data.SecurityWpaAkmFtSae.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/auth-key-mgmt-ft-sae")
	}
	if !data.SecurityWpaAkmSae.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/auth-key-mgmt-sae")
	}
	if !data.SecurityWpaAkmFtPsk.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/auth-key-mgmt-ft-psk")
	}
	if !data.SecurityWpaAkmPsk.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/auth-key-mgmt-psk")
	}
	if !data.SecurityWpaAkmFtDot1x.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/auth-key-mgmt-ft-dot1x")
	}
	if !data.SecurityWpaAkmDot1x.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/auth-key-mgmt-dot1x")
	}
	if !data.PeerBlocking.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/apf-vap-id-data/p2p-block-action")
	}
	if !data.CcxAironetIesupport.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/apf-vap-id-data/ccx-aironet-ie")
	}
	if !data.BroadcastSsid.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/apf-vap-id-data/broadcast-ssid")
	}
	if !data.WlanStatus.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/apf-vap-id-data/wlan-status")
	}
	if !data.Ssid.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/apf-vap-id-data/ssid")
	}
	if !data.WlanId.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wlan-id")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
