// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessPolicyProfile struct {
	Device                 types.String                                  `tfsdk:"device"`
	Id                     types.String                                  `tfsdk:"id"`
	PolicyProfileName      types.String                                  `tfsdk:"policy_profile_name"`
	Description            types.String                                  `tfsdk:"description"`
	Status                 types.Bool                                    `tfsdk:"status"`
	Vlan                   types.String                                  `tfsdk:"vlan"`
	AccountingList         types.String                                  `tfsdk:"accounting_list"`
	AaaOverride            types.Bool                                    `tfsdk:"aaa_override"`
	Nac                    types.Bool                                    `tfsdk:"nac"`
	NacType                types.String                                  `tfsdk:"nac_type"`
	SessionTimeout         types.Int64                                   `tfsdk:"session_timeout"`
	IdleTimeout            types.Int64                                   `tfsdk:"idle_timeout"`
	ExclusionlistTimeout   types.Int64                                   `tfsdk:"exclusionlist_timeout"`
	Ipv4Acl                types.String                                  `tfsdk:"ipv4_acl"`
	Ipv6Acl                types.String                                  `tfsdk:"ipv6_acl"`
	ServicePolicyInput     types.String                                  `tfsdk:"service_policy_input"`
	ServicePolicyOutput    types.String                                  `tfsdk:"service_policy_output"`
	StaticIpMobility       types.Bool                                    `tfsdk:"static_ip_mobility"`
	DhcpTlvCaching         types.Bool                                    `tfsdk:"dhcp_tlv_caching"`
	HttpTlvCaching         types.Bool                                    `tfsdk:"http_tlv_caching"`
	Ipv4FlowMonitorsInput  []WirelessPolicyProfileIpv4FlowMonitorsInput  `tfsdk:"ipv4_flow_monitors_input"`
	Ipv4FlowMonitorsOutput []WirelessPolicyProfileIpv4FlowMonitorsOutput `tfsdk:"ipv4_flow_monitors_output"`
	MobilityAnchors        []WirelessPolicyProfileMobilityAnchors        `tfsdk:"mobility_anchors"`
}
type WirelessPolicyProfileIpv4FlowMonitorsInput struct {
	Name types.String `tfsdk:"name"`
}
type WirelessPolicyProfileIpv4FlowMonitorsOutput struct {
	Name types.String `tfsdk:"name"`
}
type WirelessPolicyProfileMobilityAnchors struct {
	Ip       types.String `tfsdk:"ip"`
	Priority types.String `tfsdk:"priority"`
}

type WirelessPolicyProfileData struct {
	Device                 types.String                                      `tfsdk:"device"`
	Id                     types.String                                      `tfsdk:"id"`
	PolicyProfileName      types.String                                      `tfsdk:"policy_profile_name"`
	Description            types.String                                      `tfsdk:"description"`
	Status                 types.Bool                                        `tfsdk:"status"`
	Vlan                   types.String                                      `tfsdk:"vlan"`
	AccountingList         types.String                                      `tfsdk:"accounting_list"`
	AaaOverride            types.Bool                                        `tfsdk:"aaa_override"`
	Nac                    types.Bool                                        `tfsdk:"nac"`
	NacType                types.String                                      `tfsdk:"nac_type"`
	SessionTimeout         types.Int64                                       `tfsdk:"session_timeout"`
	IdleTimeout            types.Int64                                       `tfsdk:"idle_timeout"`
	ExclusionlistTimeout   types.Int64                                       `tfsdk:"exclusionlist_timeout"`
	Ipv4Acl                types.String                                      `tfsdk:"ipv4_acl"`
	Ipv6Acl                types.String                                      `tfsdk:"ipv6_acl"`
	ServicePolicyInput     types.String                                      `tfsdk:"service_policy_input"`
	ServicePolicyOutput    types.String                                      `tfsdk:"service_policy_output"`
	StaticIpMobility       types.Bool                                        `tfsdk:"static_ip_mobility"`
	DhcpTlvCaching         types.Bool                                        `tfsdk:"dhcp_tlv_caching"`
	HttpTlvCaching         types.Bool                                        `tfsdk:"http_tlv_caching"`
	Ipv4FlowMonitorsInput  []WirelessPolicyProfileIpv4FlowMonitorsInputData  `tfsdk:"ipv4_flow_monitors_input"`
	Ipv4FlowMonitorsOutput []WirelessPolicyProfileIpv4FlowMonitorsOutputData `tfsdk:"ipv4_flow_monitors_output"`
	MobilityAnchors        []WirelessPolicyProfileMobilityAnchorsData        `tfsdk:"mobility_anchors"`
}
type WirelessPolicyProfileIpv4FlowMonitorsInputData struct {
	Name types.String `tfsdk:"name"`
}
type WirelessPolicyProfileIpv4FlowMonitorsOutputData struct {
	Name types.String `tfsdk:"name"`
}
type WirelessPolicyProfileMobilityAnchorsData struct {
	Ip       types.String `tfsdk:"ip"`
	Priority types.String `tfsdk:"priority"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data WirelessPolicyProfile) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/wlan-policies/wlan-policy=%s", url.QueryEscape(fmt.Sprintf("%v", data.PolicyProfileName.ValueString())))
}

func (data WirelessPolicyProfileData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/wlan-policies/wlan-policy=%s", url.QueryEscape(fmt.Sprintf("%v", data.PolicyProfileName.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data WirelessPolicyProfile) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/wlan-policies/wlan-policy[policy-profile-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.PolicyProfileName.ValueString()))
	return path
}

func (data WirelessPolicyProfileData) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-wlan-cfg:wlan-cfg-data/wlan-policies/wlan-policy[policy-profile-name=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.PolicyProfileName.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data WirelessPolicyProfile) toBodyXML(ctx context.Context, config WirelessPolicyProfile) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data WirelessPolicyProfile) addToBodyXML(ctx context.Context, config WirelessPolicyProfile, body netconf.Body) netconf.Body {
	if !data.PolicyProfileName.IsNull() && !data.PolicyProfileName.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/policy-profile-name", data.PolicyProfileName.ValueString())
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/description", data.Description.ValueString())
	}
	if !data.Status.IsNull() && !data.Status.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/status", data.Status.ValueBool())
	}
	if !data.Vlan.IsNull() && !data.Vlan.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/interface-name", data.Vlan.ValueString())
	}
	if !data.AccountingList.IsNull() && !data.AccountingList.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/accounting-list", data.AccountingList.ValueString())
	}
	if !data.AaaOverride.IsNull() && !data.AaaOverride.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/aaa-policy-params/aaa-override", data.AaaOverride.ValueBool())
	}
	if !data.Nac.IsNull() && !data.Nac.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/aaa-policy-params/nac", data.Nac.ValueBool())
	}
	if !data.NacType.IsNull() && !data.NacType.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/aaa-policy-params/nac-type", data.NacType.ValueString())
	}
	if !data.SessionTimeout.IsNull() && !data.SessionTimeout.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wlan-timeout/session-timeout", strconv.FormatInt(data.SessionTimeout.ValueInt64(), 10))
	}
	if !data.IdleTimeout.IsNull() && !data.IdleTimeout.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wlan-timeout/idle-timeout", strconv.FormatInt(data.IdleTimeout.ValueInt64(), 10))
	}
	if !data.ExclusionlistTimeout.IsNull() && !data.ExclusionlistTimeout.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/blacklist-params/blacklist-timeout", strconv.FormatInt(data.ExclusionlistTimeout.ValueInt64(), 10))
	}
	if !data.Ipv4Acl.IsNull() && !data.Ipv4Acl.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wlan-acl/ipv4-acl", data.Ipv4Acl.ValueString())
	}
	if !data.Ipv6Acl.IsNull() && !data.Ipv6Acl.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wlan-acl/ipv6-acl", data.Ipv6Acl.ValueString())
	}
	if !data.ServicePolicyInput.IsNull() && !data.ServicePolicyInput.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/per-ssid-qos/ingress-service-name", data.ServicePolicyInput.ValueString())
	}
	if !data.ServicePolicyOutput.IsNull() && !data.ServicePolicyOutput.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/per-ssid-qos/egress-service-name", data.ServicePolicyOutput.ValueString())
	}
	if !data.StaticIpMobility.IsNull() && !data.StaticIpMobility.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/static-ip-mobility/is-static-ip-mobility", data.StaticIpMobility.ValueBool())
	}
	if !data.DhcpTlvCaching.IsNull() && !data.DhcpTlvCaching.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wlan-local-profiling/dhcp-tlv-caching", data.DhcpTlvCaching.ValueBool())
	}
	if !data.HttpTlvCaching.IsNull() && !data.HttpTlvCaching.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/wlan-local-profiling/http-tlv-caching", data.HttpTlvCaching.ValueBool())
	}
	if len(data.Ipv4FlowMonitorsInput) > 0 {
		for _, item := range data.Ipv4FlowMonitorsInput {
			cBody := netconf.Body{}
			if !item.Name.IsNull() && !item.Name.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "name", item.Name.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/avc-ipv4-fm-ingress-entries/avc-ipv4-fm-ingress-entry", cBody.Res())
		}
	}
	if len(data.Ipv4FlowMonitorsOutput) > 0 {
		for _, item := range data.Ipv4FlowMonitorsOutput {
			cBody := netconf.Body{}
			if !item.Name.IsNull() && !item.Name.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "name", item.Name.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/avc-ipv4-fm-egress-entries/avc-ipv4-fm-egress-entry", cBody.Res())
		}
	}
	if len(data.MobilityAnchors) > 0 {
		for _, item := range data.MobilityAnchors {
			cBody := netconf.Body{}
			if !item.Ip.IsNull() && !item.Ip.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "ip", item.Ip.ValueString())
			}
			if !item.Priority.IsNull() && !item.Priority.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "anchor-priority", item.Priority.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/guest-mm-db-export-entries/guest-mm-db-export-entry", cBody.Res())
		}
	}
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *WirelessPolicyProfile) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/policy-profile-name"); value.Exists() && !data.PolicyProfileName.IsNull() {
		data.PolicyProfileName = types.StringValue(value.String())
	} else {
		data.PolicyProfileName = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/status"); !data.Status.IsNull() {
		if value.Exists() {
			data.Status = types.BoolValue(value.Bool())
		}
	} else {
		data.Status = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/interface-name"); value.Exists() && !data.Vlan.IsNull() {
		data.Vlan = types.StringValue(value.String())
	} else {
		data.Vlan = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/accounting-list"); value.Exists() && !data.AccountingList.IsNull() {
		data.AccountingList = types.StringValue(value.String())
	} else {
		data.AccountingList = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/aaa-override"); !data.AaaOverride.IsNull() {
		if value.Exists() {
			data.AaaOverride = types.BoolValue(value.Bool())
		}
	} else {
		data.AaaOverride = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/nac"); !data.Nac.IsNull() {
		if value.Exists() {
			data.Nac = types.BoolValue(value.Bool())
		}
	} else {
		data.Nac = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/nac-type"); value.Exists() && !data.NacType.IsNull() {
		data.NacType = types.StringValue(value.String())
	} else {
		data.NacType = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-timeout/session-timeout"); value.Exists() && !data.SessionTimeout.IsNull() {
		data.SessionTimeout = types.Int64Value(value.Int())
	} else {
		data.SessionTimeout = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-timeout/idle-timeout"); value.Exists() && !data.IdleTimeout.IsNull() {
		data.IdleTimeout = types.Int64Value(value.Int())
	} else {
		data.IdleTimeout = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/blacklist-params/blacklist-timeout"); value.Exists() && !data.ExclusionlistTimeout.IsNull() {
		data.ExclusionlistTimeout = types.Int64Value(value.Int())
	} else {
		data.ExclusionlistTimeout = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-acl/ipv4-acl"); value.Exists() && !data.Ipv4Acl.IsNull() {
		data.Ipv4Acl = types.StringValue(value.String())
	} else {
		data.Ipv4Acl = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-acl/ipv6-acl"); value.Exists() && !data.Ipv6Acl.IsNull() {
		data.Ipv6Acl = types.StringValue(value.String())
	} else {
		data.Ipv6Acl = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/per-ssid-qos/ingress-service-name"); value.Exists() && !data.ServicePolicyInput.IsNull() {
		data.ServicePolicyInput = types.StringValue(value.String())
	} else {
		data.ServicePolicyInput = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/per-ssid-qos/egress-service-name"); value.Exists() && !data.ServicePolicyOutput.IsNull() {
		data.ServicePolicyOutput = types.StringValue(value.String())
	} else {
		data.ServicePolicyOutput = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/static-ip-mobility/is-static-ip-mobility"); !data.StaticIpMobility.IsNull() {
		if value.Exists() {
			data.StaticIpMobility = types.BoolValue(value.Bool())
		}
	} else {
		data.StaticIpMobility = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-local-profiling/dhcp-tlv-caching"); !data.DhcpTlvCaching.IsNull() {
		if value.Exists() {
			data.DhcpTlvCaching = types.BoolValue(value.Bool())
		}
	} else {
		data.DhcpTlvCaching = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-local-profiling/http-tlv-caching"); !data.HttpTlvCaching.IsNull() {
		if value.Exists() {
			data.HttpTlvCaching = types.BoolValue(value.Bool())
		}
	} else {
		data.HttpTlvCaching = types.BoolNull()
	}
	for i := range data.Ipv4FlowMonitorsInput {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Ipv4FlowMonitorsInput[i].Name.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/avc-ipv4-fm-ingress-entries/avc-ipv4-fm-ingress-entry").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "name"); value.Exists() && !data.Ipv4FlowMonitorsInput[i].Name.IsNull() {
			data.Ipv4FlowMonitorsInput[i].Name = types.StringValue(value.String())
		} else {
			data.Ipv4FlowMonitorsInput[i].Name = types.StringNull()
		}
	}
	for i := range data.Ipv4FlowMonitorsOutput {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Ipv4FlowMonitorsOutput[i].Name.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/avc-ipv4-fm-egress-entries/avc-ipv4-fm-egress-entry").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "name"); value.Exists() && !data.Ipv4FlowMonitorsOutput[i].Name.IsNull() {
			data.Ipv4FlowMonitorsOutput[i].Name = types.StringValue(value.String())
		} else {
			data.Ipv4FlowMonitorsOutput[i].Name = types.StringNull()
		}
	}
	for i := range data.MobilityAnchors {
		keys := [...]string{"ip"}
		keyValues := [...]string{data.MobilityAnchors[i].Ip.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/guest-mm-db-export-entries/guest-mm-db-export-entry").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "ip"); value.Exists() && !data.MobilityAnchors[i].Ip.IsNull() {
			data.MobilityAnchors[i].Ip = types.StringValue(value.String())
		} else {
			data.MobilityAnchors[i].Ip = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "anchor-priority"); value.Exists() && !data.MobilityAnchors[i].Priority.IsNull() {
			data.MobilityAnchors[i].Priority = types.StringValue(value.String())
		} else {
			data.MobilityAnchors[i].Priority = types.StringNull()
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *WirelessPolicyProfile) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/status"); value.Exists() {
		data.Status = types.BoolValue(value.Bool())
	} else {
		data.Status = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/interface-name"); value.Exists() {
		data.Vlan = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/accounting-list"); value.Exists() {
		data.AccountingList = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/aaa-override"); value.Exists() {
		data.AaaOverride = types.BoolValue(value.Bool())
	} else {
		data.AaaOverride = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/nac"); value.Exists() {
		data.Nac = types.BoolValue(value.Bool())
	} else {
		data.Nac = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/nac-type"); value.Exists() {
		data.NacType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-timeout/session-timeout"); value.Exists() {
		data.SessionTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-timeout/idle-timeout"); value.Exists() {
		data.IdleTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/blacklist-params/blacklist-timeout"); value.Exists() {
		data.ExclusionlistTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-acl/ipv4-acl"); value.Exists() {
		data.Ipv4Acl = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-acl/ipv6-acl"); value.Exists() {
		data.Ipv6Acl = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/per-ssid-qos/ingress-service-name"); value.Exists() {
		data.ServicePolicyInput = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/per-ssid-qos/egress-service-name"); value.Exists() {
		data.ServicePolicyOutput = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/static-ip-mobility/is-static-ip-mobility"); value.Exists() {
		data.StaticIpMobility = types.BoolValue(value.Bool())
	} else {
		data.StaticIpMobility = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-local-profiling/dhcp-tlv-caching"); value.Exists() {
		data.DhcpTlvCaching = types.BoolValue(value.Bool())
	} else {
		data.DhcpTlvCaching = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-local-profiling/http-tlv-caching"); value.Exists() {
		data.HttpTlvCaching = types.BoolValue(value.Bool())
	} else {
		data.HttpTlvCaching = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/avc-ipv4-fm-ingress-entries/avc-ipv4-fm-ingress-entry"); value.Exists() {
		data.Ipv4FlowMonitorsInput = make([]WirelessPolicyProfileIpv4FlowMonitorsInput, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := WirelessPolicyProfileIpv4FlowMonitorsInput{}
			if cValue := helpers.GetFromXPath(v, "name"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			}
			data.Ipv4FlowMonitorsInput = append(data.Ipv4FlowMonitorsInput, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/avc-ipv4-fm-egress-entries/avc-ipv4-fm-egress-entry"); value.Exists() {
		data.Ipv4FlowMonitorsOutput = make([]WirelessPolicyProfileIpv4FlowMonitorsOutput, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := WirelessPolicyProfileIpv4FlowMonitorsOutput{}
			if cValue := helpers.GetFromXPath(v, "name"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			}
			data.Ipv4FlowMonitorsOutput = append(data.Ipv4FlowMonitorsOutput, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/guest-mm-db-export-entries/guest-mm-db-export-entry"); value.Exists() {
		data.MobilityAnchors = make([]WirelessPolicyProfileMobilityAnchors, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := WirelessPolicyProfileMobilityAnchors{}
			if cValue := helpers.GetFromXPath(v, "ip"); cValue.Exists() {
				item.Ip = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "anchor-priority"); cValue.Exists() {
				item.Priority = types.StringValue(cValue.String())
			}
			data.MobilityAnchors = append(data.MobilityAnchors, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *WirelessPolicyProfileData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/status"); value.Exists() {
		data.Status = types.BoolValue(value.Bool())
	} else {
		data.Status = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/interface-name"); value.Exists() {
		data.Vlan = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/accounting-list"); value.Exists() {
		data.AccountingList = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/aaa-override"); value.Exists() {
		data.AaaOverride = types.BoolValue(value.Bool())
	} else {
		data.AaaOverride = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/nac"); value.Exists() {
		data.Nac = types.BoolValue(value.Bool())
	} else {
		data.Nac = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/aaa-policy-params/nac-type"); value.Exists() {
		data.NacType = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-timeout/session-timeout"); value.Exists() {
		data.SessionTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-timeout/idle-timeout"); value.Exists() {
		data.IdleTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/blacklist-params/blacklist-timeout"); value.Exists() {
		data.ExclusionlistTimeout = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-acl/ipv4-acl"); value.Exists() {
		data.Ipv4Acl = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-acl/ipv6-acl"); value.Exists() {
		data.Ipv6Acl = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/per-ssid-qos/ingress-service-name"); value.Exists() {
		data.ServicePolicyInput = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/per-ssid-qos/egress-service-name"); value.Exists() {
		data.ServicePolicyOutput = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/static-ip-mobility/is-static-ip-mobility"); value.Exists() {
		data.StaticIpMobility = types.BoolValue(value.Bool())
	} else {
		data.StaticIpMobility = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-local-profiling/dhcp-tlv-caching"); value.Exists() {
		data.DhcpTlvCaching = types.BoolValue(value.Bool())
	} else {
		data.DhcpTlvCaching = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/wlan-local-profiling/http-tlv-caching"); value.Exists() {
		data.HttpTlvCaching = types.BoolValue(value.Bool())
	} else {
		data.HttpTlvCaching = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/avc-ipv4-fm-ingress-entries/avc-ipv4-fm-ingress-entry"); value.Exists() {
		data.Ipv4FlowMonitorsInput = make([]WirelessPolicyProfileIpv4FlowMonitorsInputData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := WirelessPolicyProfileIpv4FlowMonitorsInputData{}
			if cValue := helpers.GetFromXPath(v, "name"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			}
			data.Ipv4FlowMonitorsInput = append(data.Ipv4FlowMonitorsInput, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/avc-ipv4-fm-egress-entries/avc-ipv4-fm-egress-entry"); value.Exists() {
		data.Ipv4FlowMonitorsOutput = make([]WirelessPolicyProfileIpv4FlowMonitorsOutputData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := WirelessPolicyProfileIpv4FlowMonitorsOutputData{}
			if cValue := helpers.GetFromXPath(v, "name"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			}
			data.Ipv4FlowMonitorsOutput = append(data.Ipv4FlowMonitorsOutput, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/guest-mm-db-export-entries/guest-mm-db-export-entry"); value.Exists() {
		data.MobilityAnchors = make([]WirelessPolicyProfileMobilityAnchorsData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := WirelessPolicyProfileMobilityAnchorsData{}
			if cValue := helpers.GetFromXPath(v, "ip"); cValue.Exists() {
				item.Ip = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "anchor-priority"); cValue.Exists() {
				item.Priority = types.StringValue(cValue.String())
			}
			data.MobilityAnchors = append(data.MobilityAnchors, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *WirelessPolicyProfile) addDeletedItemsXML(ctx context.Context, state WirelessPolicyProfile, body string) string {
	b := netconf.NewBody(body)
	for i := range state.MobilityAnchors {
		stateKeys := [...]string{"ip"}
		stateKeyValues := [...]string{state.MobilityAnchors[i].Ip.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.MobilityAnchors[i].Ip.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.MobilityAnchors {
			found = true
			if state.MobilityAnchors[i].Ip.ValueString() != data.MobilityAnchors[j].Ip.ValueString() {
				found = false
			}
			if found {
				if !state.MobilityAnchors[i].Priority.IsNull() && data.MobilityAnchors[j].Priority.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/guest-mm-db-export-entries/guest-mm-db-export-entry%v/anchor-priority", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/guest-mm-db-export-entries/guest-mm-db-export-entry%v", predicates))
		}
	}
	for i := range state.Ipv4FlowMonitorsOutput {
		stateKeys := [...]string{"name"}
		stateKeyValues := [...]string{state.Ipv4FlowMonitorsOutput[i].Name.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Ipv4FlowMonitorsOutput[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Ipv4FlowMonitorsOutput {
			found = true
			if state.Ipv4FlowMonitorsOutput[i].Name.ValueString() != data.Ipv4FlowMonitorsOutput[j].Name.ValueString() {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/avc-ipv4-fm-egress-entries/avc-ipv4-fm-egress-entry%v", predicates))
		}
	}
	for i := range state.Ipv4FlowMonitorsInput {
		stateKeys := [...]string{"name"}
		stateKeyValues := [...]string{state.Ipv4FlowMonitorsInput[i].Name.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Ipv4FlowMonitorsInput[i].Name.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Ipv4FlowMonitorsInput {
			found = true
			if state.Ipv4FlowMonitorsInput[i].Name.ValueString() != data.Ipv4FlowMonitorsInput[j].Name.ValueString() {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/avc-ipv4-fm-ingress-entries/avc-ipv4-fm-ingress-entry%v", predicates))
		}
	}
	if !state.HttpTlvCaching.IsNull() && data.HttpTlvCaching.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wlan-local-profiling/http-tlv-caching")
	}
	if !state.DhcpTlvCaching.IsNull() && data.DhcpTlvCaching.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wlan-local-profiling/dhcp-tlv-caching")
	}
	if !state.StaticIpMobility.IsNull() && data.StaticIpMobility.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/static-ip-mobility/is-static-ip-mobility")
	}
	if !state.ServicePolicyOutput.IsNull() && data.ServicePolicyOutput.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/per-ssid-qos/egress-service-name")
	}
	if !state.ServicePolicyInput.IsNull() && data.ServicePolicyInput.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/per-ssid-qos/ingress-service-name")
	}
	if !state.Ipv6Acl.IsNull() && data.Ipv6Acl.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wlan-acl/ipv6-acl")
	}
	if !state.Ipv4Acl.IsNull() && data.Ipv4Acl.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wlan-acl/ipv4-acl")
	}
	if !state.ExclusionlistTimeout.IsNull() && data.ExclusionlistTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/blacklist-params/blacklist-timeout")
	}
	if !state.IdleTimeout.IsNull() && data.IdleTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wlan-timeout/idle-timeout")
	}
	if !state.SessionTimeout.IsNull() && data.SessionTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/wlan-timeout/session-timeout")
	}
	if !state.NacType.IsNull() && data.NacType.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/aaa-policy-params/nac-type")
	}
	if !state.Nac.IsNull() && data.Nac.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/aaa-policy-params/nac")
	}
	if !state.AaaOverride.IsNull() && data.AaaOverride.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/aaa-policy-params/aaa-override")
	}
	if !state.AccountingList.IsNull() && data.AccountingList.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/accounting-list")
	}
	if !state.Vlan.IsNull() && data.Vlan.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/interface-name")
	}
	if !state.Status.IsNull() && data.Status.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/status")
	}
	if !state.Description.IsNull() && data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *WirelessPolicyProfile) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.MobilityAnchors {
		keys := [...]string{"ip"}
		keyValues := [...]string{data.MobilityAnchors[i].Ip.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/guest-mm-db-export-entries/guest-mm-db-export-entry%v", predicates))
	}
	for i := range data.Ipv4FlowMonitorsOutput {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Ipv4FlowMonitorsOutput[i].Name.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/avc-ipv4-fm-egress-entries/avc-ipv4-fm-egress-entry%v", predicates))
	}
	for i := range data.Ipv4FlowMonitorsInput {
		keys := [...]string{"name"}
		keyValues := [...]string{data.Ipv4FlowMonitorsInput[i].Name.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/avc-ipv4-fm-ingress-entries/avc-ipv4-fm-ingress-entry%v", predicates))
	}
	if !data.HttpTlvCaching.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wlan-local-profiling/http-tlv-caching")
	}
	if !data.DhcpTlvCaching.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wlan-local-profiling/dhcp-tlv-caching")
	}
	if !data.StaticIpMobility.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/static-ip-mobility/is-static-ip-mobility")
	}
	if !data.ServicePolicyOutput.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/per-ssid-qos/egress-service-name")
	}
	if !data.ServicePolicyInput.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/per-ssid-qos/ingress-service-name")
	}
	if !data.Ipv6Acl.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wlan-acl/ipv6-acl")
	}
	if !data.Ipv4Acl.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wlan-acl/ipv4-acl")
	}
	if !data.ExclusionlistTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/blacklist-params/blacklist-timeout")
	}
	if !data.IdleTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wlan-timeout/idle-timeout")
	}
	if !data.SessionTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/wlan-timeout/session-timeout")
	}
	if !data.NacType.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/aaa-policy-params/nac-type")
	}
	if !data.Nac.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/aaa-policy-params/nac")
	}
	if !data.AaaOverride.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/aaa-policy-params/aaa-override")
	}
	if !data.AccountingList.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/accounting-list")
	}
	if !data.Vlan.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/interface-name")
	}
	if !data.Status.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/status")
	}
	if !data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/description")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
