// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessRFProfile struct {
	Device                      types.String                          `tfsdk:"device"`
	Id                          types.String                          `tfsdk:"id"`
	Name                        types.String                          `tfsdk:"name"`
	Band                        types.String                          `tfsdk:"band"`
	Status                      types.Bool                            `tfsdk:"status"`
	Description                 types.String                          `tfsdk:"description"`
	DataRate1m                  types.String                          `tfsdk:"data_rate_1m"`
	DataRate2m                  types.String                          `tfsdk:"data_rate_2m"`
	DataRate55m                 types.String                          `tfsdk:"data_rate_5_5m"`
	DataRate11m                 types.String                          `tfsdk:"data_rate_11m"`
	DataRate6m                  types.String                          `tfsdk:"data_rate_6m"`
	DataRate9m                  types.String                          `tfsdk:"data_rate_9m"`
	DataRate12m                 types.String                          `tfsdk:"data_rate_12m"`
	DataRate18m                 types.String                          `tfsdk:"data_rate_18m"`
	DataRate24m                 types.String                          `tfsdk:"data_rate_24m"`
	DataRate36m                 types.String                          `tfsdk:"data_rate_36m"`
	DataRate48m                 types.String                          `tfsdk:"data_rate_48m"`
	DataRate54m                 types.String                          `tfsdk:"data_rate_54m"`
	BandSelectClientRssi        types.Int64                           `tfsdk:"band_select_client_rssi"`
	BandSelectCycleCount        types.Int64                           `tfsdk:"band_select_cycle_count"`
	BandSelectCycleThreshold    types.Int64                           `tfsdk:"band_select_cycle_threshold"`
	BandSelectExpireDualBand    types.Int64                           `tfsdk:"band_select_expire_dual_band"`
	BandSelectExpireSuppression types.Int64                           `tfsdk:"band_select_expire_suppression"`
	DcaAllowedChannels          []WirelessRFProfileDcaAllowedChannels `tfsdk:"dca_allowed_channels"`
	CoverageDataRssiThreshold   types.Int64                           `tfsdk:"coverage_data_rssi_threshold"`
	CoverageVoiceRssiThreshold  types.Int64                           `tfsdk:"coverage_voice_rssi_threshold"`
	CoverageLevelGlobal         types.Int64                           `tfsdk:"coverage_level_global"`
	LoadBalancingWindow         types.Int64                           `tfsdk:"load_balancing_window"`
	LoadBalancingDenial         types.Int64                           `tfsdk:"load_balancing_denial"`
	MaxClients                  types.Int64                           `tfsdk:"max_clients"`
	TxPowerV1Threshold          types.Int64                           `tfsdk:"tx_power_v1_threshold"`
	TxPowerMax                  types.Int64                           `tfsdk:"tx_power_max"`
	TxPowerMin                  types.Int64                           `tfsdk:"tx_power_min"`
	TrapThresholdClients        types.Int64                           `tfsdk:"trap_threshold_clients"`
	TrapThresholdInterference   types.Int64                           `tfsdk:"trap_threshold_interference"`
	TrapThresholdNoise          types.Int64                           `tfsdk:"trap_threshold_noise"`
}
type WirelessRFProfileDcaAllowedChannels struct {
	Channel types.Int64 `tfsdk:"channel"`
}

type WirelessRFProfileData struct {
	Device                      types.String                              `tfsdk:"device"`
	Id                          types.String                              `tfsdk:"id"`
	Name                        types.String                              `tfsdk:"name"`
	Band                        types.String                              `tfsdk:"band"`
	Status                      types.Bool                                `tfsdk:"status"`
	Description                 types.String                              `tfsdk:"description"`
	DataRate1m                  types.String                              `tfsdk:"data_rate_1m"`
	DataRate2m                  types.String                              `tfsdk:"data_rate_2m"`
	DataRate55m                 types.String                              `tfsdk:"data_rate_5_5m"`
	DataRate11m                 types.String                              `tfsdk:"data_rate_11m"`
	DataRate6m                  types.String                              `tfsdk:"data_rate_6m"`
	DataRate9m                  types.String                              `tfsdk:"data_rate_9m"`
	DataRate12m                 types.String                              `tfsdk:"data_rate_12m"`
	DataRate18m                 types.String                              `tfsdk:"data_rate_18m"`
	DataRate24m                 types.String                              `tfsdk:"data_rate_24m"`
	DataRate36m                 types.String                              `tfsdk:"data_rate_36m"`
	DataRate48m                 types.String                              `tfsdk:"data_rate_48m"`
	DataRate54m                 types.String                              `tfsdk:"data_rate_54m"`
	BandSelectClientRssi        types.Int64                               `tfsdk:"band_select_client_rssi"`
	BandSelectCycleCount        types.Int64                               `tfsdk:"band_select_cycle_count"`
	BandSelectCycleThreshold    types.Int64                               `tfsdk:"band_select_cycle_threshold"`
	BandSelectExpireDualBand    types.Int64                               `tfsdk:"band_select_expire_dual_band"`
	BandSelectExpireSuppression types.Int64                               `tfsdk:"band_select_expire_suppression"`
	DcaAllowedChannels          []WirelessRFProfileDcaAllowedChannelsData `tfsdk:"dca_allowed_channels"`
	CoverageDataRssiThreshold   types.Int64                               `tfsdk:"coverage_data_rssi_threshold"`
	CoverageVoiceRssiThreshold  types.Int64                               `tfsdk:"coverage_voice_rssi_threshold"`
	CoverageLevelGlobal         types.Int64                               `tfsdk:"coverage_level_global"`
	LoadBalancingWindow         types.Int64                               `tfsdk:"load_balancing_window"`
	LoadBalancingDenial         types.Int64                               `tfsdk:"load_balancing_denial"`
	MaxClients                  types.Int64                               `tfsdk:"max_clients"`
	TxPowerV1Threshold          types.Int64                               `tfsdk:"tx_power_v1_threshold"`
	TxPowerMax                  types.Int64                               `tfsdk:"tx_power_max"`
	TxPowerMin                  types.Int64                               `tfsdk:"tx_power_min"`
	TrapThresholdClients        types.Int64                               `tfsdk:"trap_threshold_clients"`
	TrapThresholdInterference   types.Int64                               `tfsdk:"trap_threshold_interference"`
	TrapThresholdNoise          types.Int64                               `tfsdk:"trap_threshold_noise"`
}
type WirelessRFProfileDcaAllowedChannelsData struct {
	Channel types.Int64 `tfsdk:"channel"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data WirelessRFProfile) getPath() string {
	return "Cisco-IOS-XE-wireless-rf-cfg:rf-cfg-data/rf-profiles/rf-profile=%s"
}

func (data WirelessRFProfileData) getPath() string {
	return "Cisco-IOS-XE-wireless-rf-cfg:rf-cfg-data/rf-profiles/rf-profile=%s"
}

// getXPath returns the XPath for NETCONF operations
func (data WirelessRFProfile) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-rf-cfg:rf-cfg-data/rf-profiles/rf-profile[name=%s]"
	return path
}

func (data WirelessRFProfileData) getXPath() string {
	path := "/Cisco-IOS-XE-wireless-rf-cfg:rf-cfg-data/rf-profiles/rf-profile[name=%s]"
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data WirelessRFProfile) toBodyXML(ctx context.Context, config WirelessRFProfile) string {
	body := data.addToBodyXML(ctx, config, netconf.Body{})
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// addToBodyXML adds this object to an existing body instead of starting from an empty one. Bulk
// resources use this to serialize all of their items into a single NETCONF payload.
func (data WirelessRFProfile) addToBodyXML(ctx context.Context, config WirelessRFProfile, body netconf.Body) netconf.Body {
	return body
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *WirelessRFProfile) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *WirelessRFProfile) fromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *WirelessRFProfileData) fromBodyXML(ctx context.Context, res xmldot.Result) {
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *WirelessRFProfile) addDeletedItemsXML(ctx context.Context, state WirelessRFProfile, body string) string {
	b := netconf.NewBody(body)

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *WirelessRFProfile) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
