// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure provider defined types fully satisfy framework interfaces
var (
	_ resource.Resource                = &WirelessAPJoinProfileResource{}
	_ resource.ResourceWithImportState = &WirelessAPJoinProfileResource{}
)

func NewWirelessAPJoinProfileResource() resource.Resource {
	return &WirelessAPJoinProfileResource{}
}

type WirelessAPJoinProfileResource struct {
	data *IosxeProviderData
}

func (r *WirelessAPJoinProfileResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_ap_join_profile"
}

func (r *WirelessAPJoinProfileResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This resource can manage the Wireless AP Join Profile configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the object.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The ap configuration profile name").String,
				Required:            true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`[!-~]([ -~]*[!-~])?`), ""),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Description for the ap configuration profile").String,
				Optional:            true,
			},
			"capwap_window_size": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("CAPWAP window size for request packets in multiwindow queue").AddIntegerRangeDescription(1, 50).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 50),
				},
			},
			"country": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP country code").AddStringEnumDescription("ad", "ae", "af", "ag", "ai", "al", "am", "ao", "aq", "ar", "as", "at", "au", "aw", "ax", "az", "ba", "bb", "bd", "be", "bf", "bg", "bh", "bi", "bj", "bl", "bm", "bn", "bo", "bq", "br", "bs", "bt", "bv", "bw", "by", "bz", "ca", "cc", "cd", "cf", "cg", "ch", "ci", "ck", "cl", "cm", "cn", "co", "cr", "cu", "cv", "cw", "cx", "cy", "cz", "de", "dj", "dk", "dm", "do", "dz", "ec", "ee", "eg", "eh", "el", "er", "es", "et", "fi", "fj", "fk", "fm", "fo", "fr", "ga", "gb", "gd", "ge", "gf", "gg", "gh", "gi", "gl", "gm", "gn", "gp", "gq", "gr", "gs", "gt", "gu", "gw", "gy", "hk", "hm", "hn", "hr", "ht", "hu", "id", "ie", "il", "im", "in", "io", "iq", "ir", "is", "it", "j2", "j3", "j4", "je", "jm", "jo", "jp", "ke", "kg", "kh", "ki", "km", "kn", "kp", "kr", "kw", "ky", "kz", "la", "lb", "lc", "li", "lk", "lr", "ls", "lt", "lu", "lv", "ly", "ma", "mc", "md", "me", "mf", "mg", "mh", "mk", "ml", "mm", "mn", "mo", "mp", "mq", "mr", "ms", "mt", "mu", "mv", "mw", "mx", "my", "mz", "na", "nc", "ne", "nf", "ng", "ni", "nl", "no", "np", "nr", "nu", "nz", "om", "pa", "pe", "pf", "pg", "ph", "pk", "pl", "pm", "pn", "pr", "ps", "pt", "pw", "py", "qa", "re", "ro", "rs", "ru", "rw", "sa", "sb", "sc", "sd", "se", "sg", "sh", "si", "sj", "sk", "sl", "sm", "sn", "so", "sr", "ss", "st", "sv", "sx", "sy", "sz", "tc", "td", "tf", "tg", "th", "ti", "tj", "tk", "tl", "tm", "tn", "to", "tr", "tt", "tv", "tw", "tz", "ua", "ug", "um", "unconfigured", "us", "uy", "uz", "va", "vc", "ve", "vg", "vi", "vn", "vu", "wf", "ws", "xk", "ye", "yt", "za", "zm", "zw").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("ad", "ae", "af", "ag", "ai", "al", "am", "ao", "aq", "ar", "as", "at", "au", "aw", "ax", "az", "ba", "bb", "bd", "be", "bf", "bg", "bh", "bi", "bj", "bl", "bm", "bn", "bo", "bq", "br", "bs", "bt", "bv", "bw", "by", "bz", "ca", "cc", "cd", "cf", "cg", "ch", "ci", "ck", "cl", "cm", "cn", "co", "cr", "cu", "cv", "cw", "cx", "cy", "cz", "de", "dj", "dk", "dm", "do", "dz", "ec", "ee", "eg", "eh", "el", "er", "es", "et", "fi", "fj", "fk", "fm", "fo", "fr", "ga", "gb", "gd", "ge", "gf", "gg", "gh", "gi", "gl", "gm", "gn", "gp", "gq", "gr", "gs", "gt", "gu", "gw", "gy", "hk", "hm", "hn", "hr", "ht", "hu", "id", "ie", "il", "im", "in", "io", "iq", "ir", "is", "it", "j2", "j3", "j4", "je", "jm", "jo", "jp", "ke", "kg", "kh", "ki", "km", "kn", "kp", "kr", "kw", "ky", "kz", "la", "lb", "lc", "li", "lk", "lr", "ls", "lt", "lu", "lv", "ly", "ma", "mc", "md", "me", "mf", "mg", "mh", "mk", "ml", "mm", "mn", "mo", "mp", "mq", "mr", "ms", "mt", "mu", "mv", "mw", "mx", "my", "mz", "na", "nc", "ne", "nf", "ng", "ni", "nl", "no", "np", "nr", "nu", "nz", "om", "pa", "pe", "pf", "pg", "ph", "pk", "pl", "pm", "pn", "pr", "ps", "pt", "pw", "py", "qa", "re", "ro", "rs", "ru", "rw", "sa", "sb", "sc", "sd", "se", "sg", "sh", "si", "sj", "sk", "sl", "sm", "sn", "so", "sr", "ss", "st", "sv", "sx", "sy", "sz", "tc", "td", "tf", "tg", "th", "ti", "tj", "tk", "tl", "tm", "tn", "to", "tr", "tt", "tv", "tw", "tz", "ua", "ug", "um", "unconfigured", "us", "uy", "uz", "va", "vc", "ve", "vg", "vi", "vn", "vu", "wf", "ws", "xk", "ye", "yt", "za", "zm", "zw"),
				},
			},
			"ssh": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("This object specifies whether SSH session can be established to the AP").String,
				Optional:            true,
			},
			"mgmtuser_username": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP user management username").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 32),
				},
			},
			"mgmtuser_password": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP user management password. Following criteria should be met if wireless password policy is configured. - Default passwords (cisco, Cisco, C!sco, ci$co, ..) are not allowed. - Reverse default passwords are not allowed. - At least one lower case letter is mandatory. - At least one upper case letter is mandatory. - At least one digit is mandatory. - Special characters are allowed, but not mandatory. - More than two sequential chars or digits (e.g., abc, 123) are not allowed. - More than two repeated chars or digits (e.g., 111, aaa) are not allowed. - Minimum password length is 8. Restriction: AP management password of cleartext type must contain ASCII characters only. This rule is not implemented using constraints.").String,
				Optional:            true,
			},
			"mgmtuser_password_type": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP user management password type").AddStringEnumDescription("aes", "clear", "clear-to-aes", "clear-to-ike-aes", "clear-to-md5", "clear-to-sha", "clear-to-type7", "ike-aes", "md5", "sha", "type7").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("aes", "clear", "clear-to-aes", "clear-to-ike-aes", "clear-to-md5", "clear-to-sha", "clear-to-type7", "ike-aes", "md5", "sha", "type7"),
				},
			},
			"mgmtuser_secret": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP user management secret").String,
				Optional:            true,
			},
			"mgmtuser_secret_type": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP user management secret type").AddStringEnumDescription("aes", "clear", "clear-to-aes", "clear-to-ike-aes", "clear-to-md5", "clear-to-sha", "clear-to-type7", "ike-aes", "md5", "sha", "type7").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("aes", "clear", "clear-to-aes", "clear-to-ike-aes", "clear-to-md5", "clear-to-sha", "clear-to-type7", "ike-aes", "md5", "sha", "type7"),
				},
			},
			"ntp_ip": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("NTP server IP address").String,
				Optional:            true,
			},
			"syslog_host": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("host name").String,
				Optional:            true,
			},
			"syslog_facility": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("facility value").AddStringEnumDescription("facility-auth", "facility-cron", "facility-daemon", "facility-kern", "facility-local0", "facility-local1", "facility-local2", "facility-local3", "facility-local4", "facility-local5", "facility-local6", "facility-local7", "facility-lpr", "facility-mail", "facility-news", "facility-sys10", "facility-sys11", "facility-sys12", "facility-sys13", "facility-sys14", "facility-sys9", "facility-syslog", "facility-user", "facility-uucp").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("facility-auth", "facility-cron", "facility-daemon", "facility-kern", "facility-local0", "facility-local1", "facility-local2", "facility-local3", "facility-local4", "facility-local5", "facility-local6", "facility-local7", "facility-lpr", "facility-mail", "facility-news", "facility-sys10", "facility-sys11", "facility-sys12", "facility-sys13", "facility-sys14", "facility-sys9", "facility-syslog", "facility-user", "facility-uucp"),
				},
			},
			"syslog_level": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("log level").AddStringEnumDescription("syslog-level-alert", "syslog-level-critical", "syslog-level-debug", "syslog-level-emergency", "syslog-level-errors", "syslog-level-information", "syslog-level-notification", "syslog-level-warning").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("syslog-level-alert", "syslog-level-critical", "syslog-level-debug", "syslog-level-emergency", "syslog-level-errors", "syslog-level-information", "syslog-level-notification", "syslog-level-warning"),
				},
			},
			"apphost": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable IOX application hosting").String,
				Optional:            true,
			},
			"association_limit": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Maximum clients per AP configuration").AddIntegerRangeDescription(0, 1200).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 1200),
				},
			},
			"awips": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Flag to enable AWIPS").String,
				Optional:            true,
			},
			"awips_forensic": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Flag to enable AWIPS forensic").String,
				Optional:            true,
			},
			"capwap_retransmit_count": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("retransmit timer count").AddIntegerRangeDescription(3, 8).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(3, 8),
				},
			},
			"capwap_retransmit_interval": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("retransmit timer interval").AddIntegerRangeDescription(2, 5).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(2, 5),
				},
			},
			"capwap_timers_discovery_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("This object represents the timeout for the AP discovery").AddIntegerRangeDescription(1, 10).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
			},
			"capwap_timers_fast_heartbeat_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("This object represents the timeout value for the heart beat timer.").AddIntegerRangeDescription(0, 10).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 10),
				},
			},
			"capwap_timers_heartbeat_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("This object represents the Heartbeattimeout for the AP discovery").AddIntegerRangeDescription(1, 30).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 30),
				},
			},
			"capwap_timers_primary_discovery_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("This object represents the timeout for the primary AP discovery").AddIntegerRangeDescription(30, 3000).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(30, 3000),
				},
			},
			"capwap_timers_primed_join_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("This object represents the primed timeout for the AP discovery").AddIntegerRangeDescription(0, 43200).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 43200),
				},
			},
			"capwap_backup_primary_name": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("the AP's primary controller name").String,
				Optional:            true,
			},
			"capwap_backup_primary_ip": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("the AP's primary controller ip address").String,
				Optional:            true,
			},
			"capwap_backup_secondary_name": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("the AP's secondary controller name").String,
				Optional:            true,
			},
			"capwap_backup_secondary_ip": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("the AP's secondary controller ip address").String,
				Optional:            true,
			},
			"capwap_fallback": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Backup Controllers fallback enabled").String,
				Optional:            true,
			},
			"capwap_discovery_private": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Discovery Response from private IP is enabled or disabled").String,
				Optional:            true,
			},
			"capwap_discovery_public": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Discovery Response from public IP is enabled or disabled").String,
				Optional:            true,
			},
			"cdp": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("True if CDP enabled for the AP").String,
				Optional:            true,
			},
			"dot1x_eap_type": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Dot1x EAP auth type").AddStringEnumDescription("dot1x-eap-fast", "dot1x-eap-none", "dot1x-eap-peap", "dot1x-eap-tls").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("dot1x-eap-fast", "dot1x-eap-none", "dot1x-eap-peap", "dot1x-eap-tls"),
				},
			},
			"dot1x_username": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP dot1x authentication username").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 32),
				},
			},
			"dot1x_password": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP dot1x authentication password").String,
				Optional:            true,
			},
			"dot1x_password_type": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP dot1x authentication password type").AddStringEnumDescription("aes", "clear", "clear-to-aes", "clear-to-ike-aes", "clear-to-md5", "clear-to-sha", "clear-to-type7", "ike-aes", "md5", "sha", "type7").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("aes", "clear", "clear-to-aes", "clear-to-ike-aes", "clear-to-md5", "clear-to-sha", "clear-to-type7", "ike-aes", "md5", "sha", "type7"),
				},
			},
			"hyperlocation": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("enable hyperlocation").String,
				Optional:            true,
			},
			"ip_dhcp_fallback": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Represents AP fallback to DHCP, if AP fails to join via static IP address").String,
				Optional:            true,
			},
			"lag": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("boolean to indicate whether ap lag enabled is used").String,
				Optional:            true,
			},
			"led": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("True if LED state is enabled otherwise disabled.").String,
				Optional:            true,
			},
			"mesh_profile": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Specifies the mesh profile name for the AP").String,
				Optional:            true,
			},
			"rogue_detection_enable": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("rogue AP detection").String,
				Optional:            true,
			},
			"rogue_detection_min_rssi": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("minmum RSSI for AP rogue detection").AddIntegerRangeDescription(-128, 70).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(-128, 70),
				},
			},
			"rogue_detection_min_transient_time": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("transient interval for AP rogue detection").String,
				Optional:            true,
			},
			"rogue_detection_report_interval": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("time interval at which monitor mode report for AP rogue detection is generated").AddIntegerRangeDescription(10, 300).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(10, 300),
				},
			},
			"statistics_ap_system_monitoring_enable": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP stats collection and processing enabled").String,
				Optional:            true,
			},
			"statistics_ap_system_monitoring_alarm_enable": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP stats alarms enabled").String,
				Optional:            true,
			},
			"statistics_ap_system_monitoring_alarm_hold_time": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Alarm hold time").AddIntegerRangeDescription(0, 3600).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 3600),
				},
			},
			"statistics_ap_system_monitoring_alarm_retransmit_time": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Alarm trap retransmission time").AddIntegerRangeDescription(0, 65535).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 65535),
				},
			},
			"statistics_ap_system_monitoring_cpu_threshold": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("CPU threshold").AddIntegerRangeDescription(0, 100).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 100),
				},
			},
			"statistics_ap_system_monitoring_mem_threshold": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Memory threshold").AddIntegerRangeDescription(0, 100).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 100),
				},
			},
			"statistics_ap_system_monitoring_sampling_interval": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Sampling interval").AddIntegerRangeDescription(2, 900).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(2, 900),
				},
			},
			"statistics_ap_system_monitoring_stats_interval": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Statistics interval").AddIntegerRangeDescription(120, 900).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(120, 900),
				},
			},
			"statistics_traffic_distribution": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable/Disable client traffic distribution stats").String,
				Optional:            true,
			},
			"statistics_traffic_distribution_interval": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Interval at which AP will send the statistics").AddIntegerRangeDescription(30, 3600).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(30, 3600),
				},
			},
			"statistics_ap_radio_monitoring_enable": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("AP radio stats collection and processing enabled").String,
				Optional:            true,
			},
			"statistics_ap_radio_monitoring_sampling_interval": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Sampling interval of radio statistics").AddIntegerRangeDescription(720, 3600).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(720, 3600),
				},
			},
			"stats_timer": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("APs stats timer").AddIntegerRangeDescription(0, 65535).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 65535),
				},
			},
			"tcp_adjust_mss_enable": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("adjust mss").String,
				Optional:            true,
			},
			"tcp_adjust_mss_size": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("This object represents the Global AP TCP MSS value").AddIntegerRangeDescription(536, 1363).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(536, 1363),
				},
			},
			"ble_scan": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set the BLE scan state").String,
				Optional:            true,
			},
		},
	}
}

func (r *WirelessAPJoinProfileResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin create

func (r *WirelessAPJoinProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan, config WirelessAPJoinProfile

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.getPath()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	plan.Id = types.StringValue(plan.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.getPath()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end create

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (r *WirelessAPJoinProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state WirelessAPJoinProfile

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		imp, diags := helpers.IsFlagImporting(ctx, req)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}

		// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		filter := helpers.GetXpathFilter(state.getXPath())
		res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", state.getPath(), err))
			return
		}

		if helpers.IsGetConfigResponseEmpty(&res) && helpers.IsListPath(state.getXPath()) {
			tflog.Debug(ctx, fmt.Sprintf("%s: Resource does not exist", state.Id.ValueString()))
			resp.State.RemoveResource(ctx)
			return
		}

		// After `terraform import` we switch to a full read.
		if imp {
			state.fromBodyXML(ctx, res.Res)
		} else {
			state.updateFromBodyXML(ctx, res.Res)
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Id.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end read

// Section below is generated&owned by "gen/generator.go". //template:begin update

func (r *WirelessAPJoinProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state, config WirelessAPJoinProfile

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read state
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Update", plan.Id.ValueString()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)
		body = plan.addDeletedItemsXML(ctx, state, body)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Update finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end update

// Section below is generated&owned by "gen/generator.go". //template:begin delete

func (r *WirelessAPJoinProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state WirelessAPJoinProfile

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		deleteMode := "all"

		// NETCONF - Serialize write operations
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		if deleteMode == "all" {
			body := netconf.Body{}
			body = helpers.RemoveFromXPath(body, state.getXPath())

			if err := helpers.EditConfig(ctx, device.NetconfClient, body.Res(), device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		} else {
			body := state.addDeletePathsXML(ctx, "")

			if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Id.ValueString()))

	resp.State.RemoveResource(ctx)
}

// End of section. //template:end delete

// Section below is generated&owned by "gen/generator.go". //template:begin import

func (r *WirelessAPJoinProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, ",")
	idParts = helpers.RemoveEmptyStrings(idParts)

	if len(idParts) != 1 && len(idParts) != 2 {
		expectedIdentifier := "Expected import identifier with format: '<name>'"
		expectedIdentifier += " or '<name>,<device>'"
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("%s. Got: %q", expectedIdentifier, req.ID),
		)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), idParts[0])...)
	if len(idParts) == 2 {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("device"), idParts[len(idParts)-1])...)
	}

	// construct path for 'id' attribute
	var state WirelessAPJoinProfile
	diags := resp.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), state.getPath())...)

	helpers.SetFlagImporting(ctx, true, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end import
