// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure provider defined types fully satisfy framework interfaces
var (
	_ resource.Resource                = &WirelessWLANProfileResource{}
	_ resource.ResourceWithImportState = &WirelessWLANProfileResource{}
)

func NewWirelessWLANProfileResource() resource.Resource {
	return &WirelessWLANProfileResource{}
}

type WirelessWLANProfileResource struct {
	data *IosxeProviderData
}

func (r *WirelessWLANProfileResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireless_wlan_profile"
}

func (r *WirelessWLANProfileResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This resource can manage the Wireless WLAN Profile configuration.",

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The path of the object.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"profile_name": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("profile-name").String,
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 32),
					stringvalidator.RegexMatches(regexp.MustCompile(`[!-~]([ -~]*[!-~])?`), ""),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"wlan_id": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("wlan ID").AddIntegerRangeDescription(1, 4096).String,
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 4096),
				},
			},
			"ssid": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Represents the SSID assigned to this WLAN. The access points will broadcast this SSID on this WLAN. SSID is restricted to non control characters.").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 32),
				},
			},
			"wlan_status": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Administrative Status of ESS(WLAN). By disabling an ESS the corresponding SSID is no longer broadcasted in AP beacons.").String,
				Optional:            true,
			},
			"broadcast_ssid": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("broadcast SSID on a WLAN").String,
				Optional:            true,
			},
			"ccx_aironet_iesupport": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("This object indicates the support for the Cisco Compatible Extensions Aironet information element on this WLAN.").String,
				Optional:            true,
			},
			"peer_blocking": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Represents the name of the ACL applied to this WLAN. If it is required to remove the ACL").AddStringEnumDescription("p2p-blocking-action-none", "p2p-blocking-action-drop", "p2p-blocking-action-fwdup").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("p2p-blocking-action-none", "p2p-blocking-action-drop", "p2p-blocking-action-fwdup"),
				},
			},
			"security_wpa_akm_dot1x": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Authentication key management type 802.1x").String,
				Optional:            true,
			},
			"security_wpa_akm_ft_dot1x": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Authentication key management type 802.11r dot1x").String,
				Optional:            true,
			},
			"security_wpa_akm_psk": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Authentication key management PSK").String,
				Optional:            true,
			},
			"security_wpa_akm_ft_psk": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Authentication key management type 802.11r PSK").String,
				Optional:            true,
			},
			"security_wpa_akm_sae": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Authentication key management type SAE").String,
				Optional:            true,
			},
			"security_wpa_akm_ft_sae": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Authentication key management type FT-SAE").String,
				Optional:            true,
			},
			"security_wpa_wpa2_ciphers_aes": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("WPA2/CCMP128 support").String,
				Optional:            true,
			},
			"security_wpa_wpa2_ciphers_gcmp128": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("WPA2/GCMP128 support").String,
				Optional:            true,
			},
			"security_wpa_wpa2_ciphers_gcmp256": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("WPA2/GCMP256 support").String,
				Optional:            true,
			},
			"security_wpa_wpa3": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configures WPA3 support").String,
				Optional:            true,
			},
			"security_wpa_psk_key_format": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Authentication pre-shared key type ascii/hex").AddStringEnumDescription("key-ascii", "key-hex").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("key-ascii", "key-hex"),
				},
			},
			"security_wpa_psk_key_encryption": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Pre-shared key encryption type").AddStringEnumDescription("clear").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("clear"),
				},
			},
			"security_wpa_psk_key": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Authentication pre-shared key. For hexadecimal key format, PSK length must be exactly 64 characters and for ASCII key format, PSK length must be in the range of 8 and 63").String,
				Optional:            true,
				Sensitive:           true,
			},
			"security_wpa_psk_key_wo": schema.StringAttribute{
				MarkdownDescription: "The write-only value of the attribute.",
				WriteOnly:           true,
				Optional:            true,
			},
			"security_wpa_psk_key_wo_version": schema.Int64Attribute{
				MarkdownDescription: "The write-only version of the attribute.",
				Optional:            true,
			},
			"security_dot1x_authentication_list": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enter the Authentication list name").String,
				Optional:            true,
			},
			"security_web_auth": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configures Web authentication").String,
				Optional:            true,
			},
			"security_web_auth_authentication_list": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enter the Authentication list name").String,
				Optional:            true,
			},
			"security_web_auth_parameter_map": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enter the parameter-map name").String,
				Optional:            true,
			},
			"security_ft": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configures Fast Transition Adaptive support").AddStringEnumDescription("dot11r-disabled", "dot11r-enabled", "dot11r-adaptive-enabled").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("dot11r-disabled", "dot11r-enabled", "dot11r-adaptive-enabled"),
				},
			},
			"security_ft_over_the_ds": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configures Fast Transition over the DS").String,
				Optional:            true,
			},
			"mac_filtering": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Set MAC filtering support on WLAN").String,
				Optional:            true,
			},
			"load_balance": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Allow/Disallow Load Balance on a WLAN").String,
				Optional:            true,
			},
			"wmm": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Configures WMM (WME)").AddStringEnumDescription("apf-vap-wme-disabled", "apf-vap-wme-allowed", "apf-vap-wme-required").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("apf-vap-wme-disabled", "apf-vap-wme-allowed", "apf-vap-wme-required"),
				},
			},
		},
	}
}

func (r *WirelessWLANProfileResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.data = req.ProviderData.(*IosxeProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin create

func (r *WirelessWLANProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan, config WirelessWLANProfile

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.getPath()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	plan.Id = types.StringValue(plan.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.getPath()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end create

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (r *WirelessWLANProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state WirelessWLANProfile

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		imp, diags := helpers.IsFlagImporting(ctx, req)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}

		// Serialize NETCONF operations when reuse disabled (concurrent reads allowed when reuse enabled)
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, false)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		filter := helpers.GetXpathFilter(state.getXPath())
		res, err := device.NetconfClient.GetConfig(ctx, "running", filter)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (%s), got error: %s", state.getPath(), err))
			return
		}

		if helpers.IsGetConfigResponseEmpty(&res) && helpers.IsListPath(state.getXPath()) {
			tflog.Debug(ctx, fmt.Sprintf("%s: Resource does not exist", state.Id.ValueString()))
			resp.State.RemoveResource(ctx)
			return
		}

		// After `terraform import` we switch to a full read.
		if imp {
			state.fromBodyXML(ctx, res.Res)
		} else {
			state.updateFromBodyXML(ctx, res.Res)
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Id.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end read

// Section below is generated&owned by "gen/generator.go". //template:begin update

func (r *WirelessWLANProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state, config WirelessWLANProfile

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read state
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Update", plan.Id.ValueString()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", plan.Device.ValueString()))
		return
	}

	if device.Managed {
		// Serialize NETCONF operations when reuse disabled, or writes when reuse enabled
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		body := plan.toBodyXML(ctx, config)
		body = plan.addDeletedItemsXML(ctx, state, body)

		if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Update finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end update

// Section below is generated&owned by "gen/generator.go". //template:begin delete

func (r *WirelessWLANProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state WirelessWLANProfile

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Id.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddAttributeError(path.Root("device"), "Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", state.Device.ValueString()))
		return
	}

	if device.Managed {
		deleteMode := "all"

		// NETCONF - Serialize write operations
		locked := helpers.AcquireNetconfLock(&device.NetconfOpMutex, device.ReuseConnection, true)
		if locked {
			defer device.NetconfOpMutex.Unlock()
		}
		defer helpers.CloseNetconfConnection(ctx, device.NetconfClient, device.ReuseConnection)

		if deleteMode == "all" {
			body := netconf.Body{}
			body = helpers.RemoveFromXPath(body, state.getXPath())

			if err := helpers.EditConfig(ctx, device.NetconfClient, body.Res(), device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		} else {
			body := state.addDeletePathsXML(ctx, "")

			if err := helpers.EditConfig(ctx, device.NetconfClient, body, device.AutoCommit); err != nil {
				resp.Diagnostics.AddError("Client Error", err.Error())
				return
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Id.ValueString()))

	resp.State.RemoveResource(ctx)
}

// End of section. //template:end delete

// Section below is generated&owned by "gen/generator.go". //template:begin import

func (r *WirelessWLANProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, ",")
	idParts = helpers.RemoveEmptyStrings(idParts)

	if len(idParts) != 1 && len(idParts) != 2 {
		expectedIdentifier := "Expected import identifier with format: '<profile_name>'"
		expectedIdentifier += " or '<profile_name>,<device>'"
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("%s. Got: %q", expectedIdentifier, req.ID),
		)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("profile_name"), idParts[0])...)
	if len(idParts) == 2 {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("device"), idParts[len(idParts)-1])...)
	}

	// construct path for 'id' attribute
	var state WirelessWLANProfile
	diags := resp.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), state.getPath())...)

	helpers.SetFlagImporting(ctx, true, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end import
